stubs/asyncpg/types.pyi:5: error: Cannot find module named 'asyncpg.pgproto.types'
stubs/ply/yacc.pyi:7: error: Cannot find module named 'stubs.ply.lex'
src/inmanta/parser/parsetab.py:5347: error: Need type annotation for '_lr_action' (hint: "_lr_action: Dict[<type>, <type>] = ...")
src/inmanta/parser/parsetab.py:5931: error: Need type annotation for '_lr_goto' (hint: "_lr_goto: Dict[<type>, <type>] = ...")
src/inmanta/command.py:31: error: Need type annotation for '__command_functions' (hint: "__command_functions: Dict[<type>, <type>] = ...")
stubs/asyncpg/exceptions/__init__.pyi:100: error: Name 'DataError' already defined (possibly by an import)
src/inmanta/agent/io/local.py:29: error: Incompatible types in assignment (expression has type "None", variable has type Module)
src/inmanta/agent/io/local.py:30: error: Incompatible types in assignment (expression has type "None", variable has type Module)
src/inmanta/agent/io/local.py:36: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[str], struct_passwd]")
src/inmanta/agent/io/local.py:41: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[str], struct_group]")
src/inmanta/agent/io/local.py:436: error: Incompatible types in assignment (expression has type "Dict[bytes, bytes]", variable has type "Dict[str, str]")
src/inmanta/agent/io/local.py:505: error: Incompatible types in assignment (expression has type "int", target has type "str")
src/inmanta/agent/io/local.py:507: error: Incompatible return value type (got "Dict[str, str]", expected "Dict[str, Union[int, str]]")
src/inmanta/agent/io/local.py:507: note: Perhaps you need a type annotation for "status"? Suggestion: "Dict[str, Union[int, str]]"
src/inmanta/agent/io/local.py:527: error: No overload variant of "write" of "BinaryIO" matches argument type "str"
src/inmanta/agent/io/local.py:527: note: Possible overload variants:
src/inmanta/agent/io/local.py:527: note:     def write(self, s: bytearray) -> int
src/inmanta/agent/io/local.py:527: note:     def write(self, s: bytes) -> int
src/inmanta/agent/io/local.py:538: error: Incompatible types in assignment (expression has type "None", variable has type "struct_group")
src/inmanta/agent/io/local.py:552: error: Incompatible types in assignment (expression has type "None", variable has type "struct_passwd")
src/inmanta/agent/io/local.py:575: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")
src/inmanta/agent/io/local.py:578: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "Optional[str]")
src/inmanta/agent/io/local.py:583: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")
src/inmanta/agent/io/local.py:585: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "Optional[str]")
src/inmanta/agent/io/local.py:589: error: Argument 2 to "chown" has incompatible type "Optional[str]"; expected "int"
src/inmanta/agent/io/local.py:589: error: Argument 3 to "chown" has incompatible type "Optional[str]"; expected "int"
src/inmanta/agent/io/local.py:628: error: Name 'channel' is not defined
src/inmanta/agent/io/local.py:633: error: Name 'channel' is not defined
src/inmanta/agent/io/local.py:637: error: Name 'channel' is not defined
stubs/asyncpg/prepared_stmt.pyi:5: error: Module 'asyncpg' has no attribute 'connresource'
stubs/asyncpg/cursor.pyi:5: error: Module 'asyncpg' has no attribute 'connresource'
stubs/asyncpg/connection.pyi:18: error: The return type of "__init__" must be None
src/inmanta/postgresproc.py:74: error: Argument 1 to "_create_sockets_dir" of "PostgresProc" has incompatible type "Optional[str]"; expected "str"
src/inmanta/postgresproc.py:76: error: Argument 1 to "chdir" has incompatible type "Optional[str]"; expected "Union[int, bytes, str, _PathLike[Any]]"
src/inmanta/postgresproc.py:78: error: Argument 1 to "Popen" has incompatible type "List[Optional[str]]"; expected "Union[bytes, str, Sequence[Union[bytes, str, _PathLike[Any]]]]"
src/inmanta/postgresproc.py:106: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"
src/inmanta/postgresproc.py:109: error: Argument 1 to "chmod" has incompatible type "Optional[str]"; expected "Union[int, bytes, str, _PathLike[Any]]"
src/inmanta/postgresproc.py:111: error: Argument 1 to "Popen" has incompatible type "List[Optional[str]]"; expected "Union[bytes, str, Sequence[Union[bytes, str, _PathLike[Any]]]]"
src/inmanta/postgresproc.py:123: error: Argument 1 to "Popen" has incompatible type "List[Optional[str]]"; expected "Union[bytes, str, Sequence[Union[bytes, str, _PathLike[Any]]]]"
src/inmanta/postgresproc.py:128: error: Value of type variable "_AnyPath" of "rmtree" cannot be "Optional[str]"
src/inmanta/postgresproc.py:135: error: Argument 1 to "Popen" has incompatible type "List[Optional[str]]"; expected "Union[bytes, str, Sequence[Union[bytes, str, _PathLike[Any]]]]"
src/inmanta/env.py:28: error: No library stub file for standard library module 'venv'
src/inmanta/env.py:102: error: "Type[WorkingSet]" has no attribute "_build_master"
src/inmanta/env.py:125: error: Module has no attribute "real_prefix"
src/inmanta/env.py:169: error: "Requirement" has no attribute "name"
src/inmanta/env.py:174: error: "Requirement" has no attribute "url"
src/inmanta/env.py:175: error: Module has no attribute "RequirementParseError"
src/inmanta/env.py:231: error: "Type[WorkingSet]" has no attribute "_build_master"
src/inmanta/db/versions/v1.py:22: error: Module "asyncpg.connection" is not valid as a type
src/inmanta/db/versions/v1.py:338: error: asyncpg.connection? has no attribute "transaction"
src/inmanta/db/versions/v1.py:339: error: asyncpg.connection? has no attribute "execute"
src/inmanta/data/schema.py:228: error: Module has no attribute "__path__"
src/inmanta/config.py:33: error: No library stub file for module 'cryptography.hazmat.backends'
src/inmanta/config.py:33: note: (Stub files are from https://github.com/python/typeshed)
src/inmanta/config.py:34: error: No library stub file for module 'cryptography.hazmat.primitives'
src/inmanta/config.py:35: error: No library stub file for module 'cryptography.hazmat.primitives.asymmetric.rsa'
src/inmanta/config.py:119: error: Incompatible return value type (got "Optional[str]", expected "Union[str, ConfigParser]")
src/inmanta/config.py:120: error: Argument 1 to "validate" of "Option" has incompatible type "Optional[str]"; expected "str"
src/inmanta/config.py:133: error: Argument 3 to "validate_option_request" of "Config" has incompatible type "Optional[bool]"; expected "Optional[str]"
src/inmanta/config.py:134: error: Argument "fallback" to "getboolean" of "RawConfigParser" has incompatible type "Optional[bool]"; expected "bool"
src/inmanta/config.py:190: error: "ConfigParser" has no attribute "_convert_to_boolean"
src/inmanta/config.py:257: error: Incompatible default for argument "validator" (default has type "Callable[[str], str]", argument has type "Callable[[str], T]")
src/inmanta/config.py:286: error: Argument 1 to "validate" of "Option" has incompatible type "Union[str, T, None]"; expected "str"
src/inmanta/config.py:427: error: Incompatible types in assignment (expression has type "AuthJWTConfig", variable has type "ConfigParser")
src/inmanta/config.py:428: error: "ConfigParser" has no attribute "sign"
src/inmanta/config.py:574: error: "URLError" has no attribute "response"
src/inmanta/server/config.py:120: error: Incompatible return value type (got "Union[str, ConfigParser]", expected "int")
src/inmanta/server/config.py:120: error: Argument 3 to "get" of "Config" has incompatible type "int"; expected "Optional[str]"
src/inmanta/server/config.py:133: error: Argument 5 to "Option" has incompatible type "Callable[[str], Optional[str]]"; expected "Callable[[str], str]"
src/inmanta/ast/__init__.py:116: error: Incompatible types in assignment (expression has type "None", variable has type "Location")
src/inmanta/ast/__init__.py:202: error: "Type" has no attribute "get_entity"
src/inmanta/ast/__init__.py:246: error: Attribute 'visible_namespaces' already defined on line 243
src/inmanta/ast/__init__.py:573: error: Argument 1 to "format_exception_only" has incompatible type "Union[Type[BaseException], Type[None]]"; expected "Optional[Type[BaseException]]"
src/inmanta/ast/__init__.py:618: error: Argument 2 to "__init__" of "RuntimeException" has incompatible type "Instance"; expected "Optional[Locatable]"
src/inmanta/agent/reporting.py:29: error: Incompatible types in assignment (expression has type "None", variable has type Module)
src/inmanta/agent/reporting.py:75: error: Cannot find module named 'netifaces'
src/inmanta/execute/proxy.py:80: error: Incompatible return value type (got "None", expected "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]")
src/inmanta/execute/proxy.py:83: error: Incompatible return value type (got "None", expected "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]")
src/inmanta/ast/type.py:197: error: Incompatible return value type (got "None", expected "int")
src/inmanta/ast/type.py:209: error: Incompatible return value type (got "float", expected "int")
src/inmanta/ast/type.py:223: error: Incompatible return value type (got "None", expected "Location")
src/inmanta/ast/type.py:275: error: Incompatible return value type (got "None", expected "Location")
src/inmanta/ast/type.py:319: error: Incompatible return value type (got "None", expected "Location")
src/inmanta/ast/type.py:410: error: Incompatible return value type (got "None", expected "Location")
src/inmanta/ast/type.py:457: error: Incompatible return value type (got "None", expected "Location")
src/inmanta/ast/type.py:500: error: Missing return statement
src/inmanta/ast/type.py:500: error: Signature of "cast" incompatible with supertype "Type"
src/inmanta/ast/type.py:504: error: "ConstraintType" has no attribute "__base_type"; maybe "basetype"?
src/inmanta/util.py:165: error: Invalid index type "Union[Callable[..., Any], Coroutine[Any, Any, Any]]" for "Dict[Callable[..., Any], object]"; expected type "Callable[..., Any]"
src/inmanta/util.py:213: error: "object" has no attribute "to_dict"
src/inmanta/util.py:241: error: Argument 1 to "add_done_callback" of "Future" has incompatible type "Callable[[Task[Any]], None]"; expected "Callable[[Future[Any]], Any]"
src/inmanta/util.py:242: error: Incompatible return value type (got "Future[Any]", expected "Task[Any]")
src/inmanta/util.py:298: error: Argument 1 to "add_done_callback" of "Future" has incompatible type "Callable[[Task[Any]], None]"; expected "Callable[[Future[Any]], Any]"
src/inmanta/util.py:299: error: Argument 1 to "add" of "set" has incompatible type "Future[Any]"; expected "Task[Any]"
src/inmanta/util.py:302: error: Argument 1 to "add" of "set" has incompatible type "Future[Any]"; expected "Task[Any]"
src/inmanta/util.py:304: error: Incompatible return value type (got "Future[Any]", expected "Task[Any]")
src/inmanta/util.py:343: error: Need type annotation for 'out' (hint: "out: List[<type>] = ...")
src/inmanta/execute/runtime.py:136: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")
src/inmanta/execute/runtime.py:142: error: Incompatible return value type (got "Optional[T]", expected "T")
src/inmanta/execute/runtime.py:194: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")
src/inmanta/execute/runtime.py:232: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")
src/inmanta/execute/runtime.py:234: error: Incompatible types in assignment (expression has type "None", variable has type "QueueScheduler")
src/inmanta/execute/runtime.py:281: error: Incompatible types in assignment (expression has type "List[ResultCollector[Union[Instance, List[Instance]]]]", base class "DelayedResultVariable" defined the type as "None")
src/inmanta/execute/runtime.py:285: error: Argument 1 to "Promise" has incompatible type "BaseListVariable"; expected "ListVariable"
src/inmanta/execute/runtime.py:313: error: "BaseListVariable" has no attribute "myself"
src/inmanta/execute/runtime.py:314: error: "BaseListVariable" has no attribute "attribute"
src/inmanta/execute/runtime.py:323: error: "BaseListVariable" has no attribute "myself"
src/inmanta/execute/runtime.py:323: error: "BaseListVariable" has no attribute "attribute"
src/inmanta/execute/runtime.py:408: error: Item "List[Instance]" of "Union[Instance, List[Instance]]" has no attribute "set_attribute"
src/inmanta/execute/runtime.py:438: error: Incompatible types in assignment (expression has type "None", variable has type "Location")
src/inmanta/execute/runtime.py:668: error: Argument 4 to "resume" of "Resumer" has incompatible type "Optional[ResultVariable[Any]]"; expected "ResultVariable[Any]"
src/inmanta/execute/runtime.py:816: error: Argument 1 to "__init__" of "Locatable" has incompatible type "Instance"; expected "Locatable"
src/inmanta/execute/runtime.py:824: error: Argument 2 to "set_value" of "ResultVariable" has incompatible type "None"; expected "Location"
src/inmanta/execute/runtime.py:842: error: Argument 1 to "AttributeException" has incompatible type "Instance"; expected "Locatable"
src/inmanta/execute/runtime.py:867: error: Argument 1 to "RuntimeException" has incompatible type "Instance"; expected "Optional[Locatable]"
src/inmanta/execute/runtime.py:915: error: Name 'set_location' already defined on line 803
src/inmanta/execute/runtime.py:916: error: Argument 1 to "set_location" of "Locatable" has incompatible type "Instance"; expected "Locatable"
src/inmanta/execute/runtime.py:919: error: Name 'get_location' already defined on line 807
src/inmanta/data/__init__.py:151: error: Incompatible types in assignment (expression has type "None", variable has type "Pool")
src/inmanta/data/__init__.py:166: error: "Type[BaseDocument]" has no attribute "_fields"
src/inmanta/data/__init__.py:218: error: "Type[BaseDocument]" has no attribute "_fields"
src/inmanta/data/__init__.py:250: error: Incompatible types in assignment (expression has type "None", variable has type "Pool")
src/inmanta/data/__init__.py:340: error: Incompatible return value type (got "Optional[Record]", expected "Record")
src/inmanta/data/__init__.py:362: error: "Type[BaseDocument]" has no attribute "_fields"
src/inmanta/data/__init__.py:368: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")
src/inmanta/data/__init__.py:432: error: "Type[T]" has no attribute "get_list"
src/inmanta/data/__init__.py:438: error: Missing return statement
src/inmanta/data/__init__.py:439: error: "Type[T]" has no attribute "get_list"
src/inmanta/data/__init__.py:456: error: "Type[T]" has no attribute "_convert_field_names_to_db_column_names"
src/inmanta/data/__init__.py:457: error: "Type[T]" has no attribute "_get_composed_filter"
src/inmanta/data/__init__.py:458: error: "Type[T]" has no attribute "table_name"
src/inmanta/data/__init__.py:467: error: "Type[T]" has no attribute "select_query"
src/inmanta/data/__init__.py:582: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:583: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:593: error: "Type[RawConfigParser]" has no attribute "BOOLEAN_STATES"
src/inmanta/data/__init__.py:595: error: "Type[RawConfigParser]" has no attribute "BOOLEAN_STATES"
src/inmanta/data/__init__.py:735: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:736: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:737: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:738: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:739: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:740: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]")
src/inmanta/data/__init__.py:741: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:777: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:784: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:792: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:800: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:808: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:823: error: Argument "validator" to "Setting" has incompatible type "Callable[[Dict[str, str]], Dict[str, str]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:832: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:847: error: Argument "validator" to "Setting" has incompatible type "Callable[[Any], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"
src/inmanta/data/__init__.py:886: error: Argument 2 to "set" of "Environment" has incompatible type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]"
src/inmanta/data/__init__.py:887: error: Incompatible return value type (got "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]], None]", expected "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]")
src/inmanta/data/__init__.py:900: error: "None" not callable
src/inmanta/data/__init__.py:933: error: Argument 2 to "set" of "Environment" has incompatible type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]"
src/inmanta/data/__init__.py:990: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:991: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:992: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:993: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:994: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:995: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceIdStr")
src/inmanta/data/__init__.py:996: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:997: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:1031: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1032: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1033: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1034: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1035: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceIdStr")
src/inmanta/data/__init__.py:1036: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:1037: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:1038: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:1050: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1051: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1052: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1053: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1054: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1055: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1081: error: Incompatible return value type (got "None", expected "List[AgentProcess]")
src/inmanta/data/__init__.py:1084: error: Incompatible return value type (got "AgentProcess", expected "List[AgentProcess]")
src/inmanta/data/__init__.py:1086: error: Incompatible return value type (got "AgentProcess", expected "List[AgentProcess]")
src/inmanta/data/__init__.py:1132: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1133: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1134: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1135: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:1136: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[UUID]")
src/inmanta/data/__init__.py:1201: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1202: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1203: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[datetime]")
src/inmanta/data/__init__.py:1204: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1205: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1206: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1207: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1208: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[int]")
src/inmanta/data/__init__.py:1209: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1240: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1241: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[UUID]")
src/inmanta/data/__init__.py:1242: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1243: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[datetime]")
src/inmanta/data/__init__.py:1244: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[datetime]")
src/inmanta/data/__init__.py:1245: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[datetime]")
src/inmanta/data/__init__.py:1247: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:1248: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:1249: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[Any, Any]")
src/inmanta/data/__init__.py:1250: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[Any, Any]")
src/inmanta/data/__init__.py:1252: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[bool]")
src/inmanta/data/__init__.py:1253: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:1254: error: Incompatible types in assignment (expression has type "Field", variable has type "Optional[int]")
src/inmanta/data/__init__.py:1290: error: Incompatible return value type (got "None", expected "Compile")
src/inmanta/data/__init__.py:1296: error: Incompatible return value type (got "Dict[str, Any]", expected "Compile")
src/inmanta/data/__init__.py:1307: error: Incompatible return value type (got "None", expected "Compile")
src/inmanta/data/__init__.py:1319: error: Incompatible return value type (got "None", expected "Compile")
src/inmanta/data/__init__.py:1387: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1388: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1389: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, str]")
src/inmanta/data/__init__.py:1390: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, str]")
src/inmanta/data/__init__.py:1391: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]")
src/inmanta/data/__init__.py:1392: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Dict[str, str]]")
src/inmanta/data/__init__.py:1401: error: Incompatible return value type (got "None", expected "Form")
src/inmanta/data/__init__.py:1416: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1417: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1418: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1419: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]")
src/inmanta/data/__init__.py:1420: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1448: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1449: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceVersionIdStr")
src/inmanta/data/__init__.py:1450: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1471: error: Incompatible types in assignment (expression has type "Field", variable has type "List[ResourceVersionIdStr]")
src/inmanta/data/__init__.py:1473: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1474: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceAction")
src/inmanta/data/__init__.py:1476: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1477: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1517: error: "ResourceAction" gets multiple values for keyword argument "from_postgres"
src/inmanta/data/__init__.py:1570: error: "ResourceAction" gets multiple values for keyword argument "from_postgres"
src/inmanta/data/__init__.py:1750: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:1751: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:1754: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceVersionIdStr")
src/inmanta/data/__init__.py:1755: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceType")
src/inmanta/data/__init__.py:1756: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceVersionIdStr")
src/inmanta/data/__init__.py:1758: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1761: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:1764: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:1765: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:1766: error: Incompatible types in assignment (expression has type "Field", variable has type "ResourceState")
src/inmanta/data/__init__.py:1771: error: Incompatible types in assignment (expression has type "Field", variable has type "List[ResourceVersionIdStr]")
src/inmanta/data/__init__.py:1881: error: Argument after ** must be a mapping, not "Record"
src/inmanta/data/__init__.py:1884: error: Argument 2 to "is_sub_dict" has incompatible type "Dict[str, Any]"; expected "Dict[Union[UUID, StrictNonIntBool, int, float, datetime, str], Union[UUID, StrictNonIntBool, int, float, datetime, str]]"
src/inmanta/data/__init__.py:1957: error: Incompatible types in assignment (expression has type "Dict[Any, Any]", variable has type "Record")
src/inmanta/data/__init__.py:1958: error: Unsupported target for indexed assignment
src/inmanta/data/__init__.py:1959: error: Unsupported target for indexed assignment
src/inmanta/data/__init__.py:1961: error: Unsupported target for indexed assignment
src/inmanta/data/__init__.py:1964: error: Argument 1 to "append" of "list" has incompatible type "Resource"; expected "Record"
src/inmanta/data/__init__.py:1964: error: Argument after ** must be a mapping, not "Record"
src/inmanta/data/__init__.py:1965: error: Incompatible return value type (got "List[Record]", expected "List[Resource]")
src/inmanta/data/__init__.py:2109: error: Argument 1 of "insert_many" is incompatible with supertype "BaseDocument"; supertype defines the argument type as "Sequence[BaseDocument]"
src/inmanta/data/__init__.py:2112: error: Argument 1 to "insert_many" of "BaseDocument" has incompatible type "Iterable[Resource]"; expected "Sequence[BaseDocument]"
src/inmanta/data/__init__.py:2156: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2157: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:2158: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:2160: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:2161: error: Incompatible types in assignment (expression has type "Field", variable has type "bool")
src/inmanta/data/__init__.py:2162: error: Incompatible types in assignment (expression has type "Field", variable has type "VersionState")
src/inmanta/data/__init__.py:2163: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:2165: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2168: error: Incompatible types in assignment (expression has type "Field", variable has type "List[ResourceIdStr]")
src/inmanta/data/__init__.py:2169: error: Incompatible types in assignment (expression has type "Field", variable has type "List[ResourceIdStr]")
src/inmanta/data/__init__.py:2192: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
src/inmanta/data/__init__.py:2197: error: Return type "Coroutine[Any, Any, List[ConfigurationModel]]" of "get_list" incompatible with return type "Coroutine[Any, Any, List[<nothing>]]" in supertype "BaseDocument"
src/inmanta/data/__init__.py:2214: error: Incompatible types in assignment (expression has type "str", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:2275: error: Incompatible return value type (got "None", expected "ConfigurationModel")
src/inmanta/data/__init__.py:2506: error: Need type annotation for 'done' (hint: "done: Set[<type>] = ...")
src/inmanta/data/__init__.py:2521: error: Argument 1 to "set" has incompatible type "Set[str]"; expected "Iterable[ResourceVersionIdStr]"
src/inmanta/data/__init__.py:2538: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:2539: error: Incompatible types in assignment (expression has type "Field", variable has type "str")
src/inmanta/data/__init__.py:2540: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2541: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Tuple[str, str, List[str]]]")
src/inmanta/data/__init__.py:2570: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:2571: error: Incompatible types in assignment (expression has type "Field", variable has type "UUID")
src/inmanta/data/__init__.py:2572: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2573: error: Incompatible types in assignment (expression has type "Field", variable has type "datetime")
src/inmanta/data/__init__.py:2574: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2575: error: Incompatible types in assignment (expression has type "Field", variable has type "int")
src/inmanta/data/__init__.py:2576: error: Incompatible types in assignment (expression has type "Field", variable has type "Dict[str, Any]")
src/inmanta/data/__init__.py:2636: error: "DocumentMeta" has no attribute "set_connection_pool"
src/inmanta/data/__init__.py:2641: error: "DocumentMeta" has no attribute "close_connection_pool"
src/inmanta/ast/statements/__init__.py:41: error: Incompatible types in assignment (expression has type "None", variable has type "Namespace")
src/inmanta/ast/statements/__init__.py:92: error: Need type annotation for 'target'
src/inmanta/ast/statements/__init__.py:212: error: Incompatible types in assignment (expression has type "None", variable has type "NamedType")
src/inmanta/ast/attribute.py:62: error: Incompatible types in assignment (expression has type "property", variable has type "Type")
src/inmanta/ast/attribute.py:101: error: Incompatible types in assignment (expression has type "Type", variable has type "TypedList")
src/inmanta/ast/attribute.py:111: error: Incompatible types in assignment (expression has type "NullableType", variable has type "TypedList")
src/inmanta/ast/attribute.py:139: error: Need type annotation for 'source_annotations' (hint: "source_annotations: List[<type>] = ...")
src/inmanta/ast/attribute.py:140: error: Need type annotation for 'target_annotations' (hint: "target_annotations: List[<type>] = ...")
src/inmanta/ast/attribute.py:159: error: Name 'out' already defined on line 157
src/inmanta/ast/attribute.py:161: error: Name 'out' already defined on line 157
src/inmanta/protocol/common.py:54: error: Cannot find module named 'typing_inspect'
src/inmanta/protocol/common.py:185: error: Dict entry 0 has incompatible type "str": "Dict[str, List[str]]"; expected "str": "Union[BaseModel, Enum, UUID, StrictNonIntBool, float, datetime, str]"
src/inmanta/protocol/common.py:796: error: Incompatible types in assignment (expression has type "str", variable has type "bytes")
src/inmanta/protocol/rest/__init__.py:25: error: Cannot find module named 'typing_inspect'
src/inmanta/protocol/rest/__init__.py:415: error: "Callable[..., Coroutine[...]]" has no attribute "__protocol_mapping__"
src/inmanta/protocol/decorators.py:51: error: "FuncT" has no attribute "__protocol_method__"
src/inmanta/protocol/decorators.py:52: error: "FuncT" has no attribute "__protocol_mapping__"
src/inmanta/protocol/decorators.py:53: error: "FuncT" has no attribute "__api_version__"
src/inmanta/protocol/rest/client.py:43: error: Incompatible types in assignment (expression has type "Union[str, ConfigParser]", variable has type "Optional[str]")
src/inmanta/protocol/rest/client.py:46: error: Incompatible types in assignment (expression has type "Union[str, ConfigParser]", variable has type "int")
src/inmanta/protocol/rest/client.py:46: error: Argument 3 to "get" of "Config" has incompatible type "int"; expected "Optional[str]"
src/inmanta/protocol/rest/client.py:70: error: Incompatible return value type (got "Tuple[Dict[str, str], UrlMethod]", expected "Tuple[Optional[Dict[str, bytes]], Optional[UrlMethod]]")
src/inmanta/protocol/rest/client.py:80: error: Incompatible types in assignment (expression has type "Union[str, ConfigParser]", variable has type "int")
src/inmanta/protocol/rest/client.py:80: error: Argument 3 to "get" of "Config" has incompatible type "int"; expected "Optional[str]"
src/inmanta/protocol/rest/client.py:81: error: Incompatible types in assignment (expression has type "Union[str, ConfigParser]", variable has type "str")
src/inmanta/protocol/rest/client.py:105: error: Incompatible types in assignment (expression has type "Union[bytes, str]", variable has type "Optional[Dict[str, Any]]")
src/inmanta/protocol/rest/client.py:113: error: Argument "body" to "HTTPRequest" has incompatible type "Optional[Dict[str, Any]]"; expected "Union[bytes, str, None]"
src/inmanta/protocol/rest/client.py:113: error: Argument "ca_certs" to "HTTPRequest" has incompatible type "Union[str, ConfigParser]"; expected "Optional[str]"
src/inmanta/protocol/methods.py:34: error: Incompatible types in assignment (expression has type "Optional[Environment]", variable has type "UUID")
src/inmanta/protocol/methods.py:37: error: Incompatible return value type (got "UUID", expected "Environment")
src/inmanta/protocol/endpoints.py:77: error: "Callable[..., Any]" has no attribute "__api_version__"
src/inmanta/protocol/endpoints.py:78: error: "Callable[..., Any]" has no attribute "__api_version__"
src/inmanta/protocol/endpoints.py:79: error: "Callable[..., Any]" has no attribute "__api_version__"
src/inmanta/protocol/endpoints.py:264: error: "str" has no attribute "decode"; maybe "encode"?
src/inmanta/protocol/endpoints.py:266: error: "str" has no attribute "decode"; maybe "encode"?
src/inmanta/protocol/endpoints.py:269: error: Argument 1 to "_execute_call" of "RESTBase" has incompatible type "Optional[Dict[str, str]]"; expected "Dict[str, str]"
src/inmanta/protocol/endpoints.py:269: error: Argument 3 to "_execute_call" of "RESTBase" has incompatible type "Optional[UrlMethod]"; expected "UrlMethod"
src/inmanta/protocol/endpoints.py:273: error: Unsupported right operand type for in ("Union[BaseModel, Enum, UUID, StrictNonIntBool, float, datetime, Sequence[Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]], Mapping[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]]")
src/inmanta/protocol/endpoints.py:274: error: Incompatible types in assignment (expression has type "Union[Any, BaseModel, Enum, UUID, StrictNonIntBool, float, datetime, str]", variable has type "str")
src/inmanta/protocol/endpoints.py:274: error: Value of type "Union[BaseModel, Enum, UUID, StrictNonIntBool, float, datetime, Sequence[Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]], Mapping[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]]" is not indexable
src/inmanta/protocol/endpoints.py:274: error: No overload variant of "__getitem__" of "Sequence" matches argument type "str"
src/inmanta/protocol/endpoints.py:274: note: Possible overload variants:
src/inmanta/protocol/endpoints.py:274: note:     def __getitem__(self, int) -> Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]
src/inmanta/protocol/endpoints.py:274: note:     def __getitem__(self, slice) -> Sequence[Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]
src/inmanta/protocol/endpoints.py:352: error: Item "None" of "Optional[MethodProperties]" has no attribute "function"
src/inmanta/protocol/endpoints.py:353: error: Incompatible return value type (got "Coroutine[Any, Any, Result]", expected "Result")
src/inmanta/protocol/endpoints.py:353: error: Argument "method_properties" to "_call" of "Client" has incompatible type "Optional[MethodProperties]"; expected "MethodProperties"
src/inmanta/protocol/endpoints.py:353: error: Argument "args" to "_call" of "Client" has incompatible type "Tuple[List[Any], ...]"; expected "List[Any]"
src/inmanta/ast/statements/assign.py:246: error: Argument 2 to "__init__" of "AssignStatement" has incompatible type "None"; expected "Reference"
src/inmanta/ast/statements/assign.py:311: error: Need type annotation for 'temp'
src/inmanta/ast/statements/assign.py:320: error: "Type" has no attribute "lookup_index"
src/inmanta/ast/statements/assign.py:354: error: Incompatible types in assignment (expression has type "None", variable has type "Type")
src/inmanta/ast/statements/assign.py:380: error: "Type" has no attribute "lookup_index"
src/inmanta/plugins.py:65: error: Too many arguments for "normalize" of "DynamicStatement"
src/inmanta/plugins.py:67: error: Unexpected keyword argument "provides" for "ExecutionUnit"
src/inmanta/execute/runtime.py:602: note: "ExecutionUnit" defined here
src/inmanta/plugins.py:135: error: Need type annotation for '__functions' (hint: "__functions: Dict[<type>, <type>] = ...")
src/inmanta/plugins.py:175: error: "Type[Plugin]" has no attribute "__function__"
src/inmanta/plugins.py:182: error: "Plugin" has no attribute "namespace"
src/inmanta/plugins.py:183: error: "Plugin" has no attribute "namespace"
src/inmanta/plugins.py:184: error: "Plugin" has no attribute "namespace"
src/inmanta/plugins.py:307: error: "Type[Plugin]" has no attribute "__function_name__"
src/inmanta/plugins.py:316: error: Incompatible return value type (got "None", expected "DynamicStatement")
src/inmanta/plugins.py:331: error: "Plugin" has no attribute "opts"
src/inmanta/plugins.py:332: error: "Plugin" has no attribute "opts"
src/inmanta/plugins.py:337: error: "Plugin" has no attribute "__function_name__"
src/inmanta/ast/variables.py:51: error: Incompatible return value type (got "Dict[str, Union[Type, ResultVariable[Any]]]", expected "Dict[object, ResultVariable[Any]]")
src/inmanta/ast/variables.py:55: error: Item "Type" of "Union[Type, ResultVariable[Any]]" has no attribute "listener"
src/inmanta/ast/variables.py:57: error: Incompatible return value type (got "Dict[str, Union[Type, ResultVariable[Any]]]", expected "Dict[object, ResultVariable[Any]]")
src/inmanta/ast/variables.py:76: error: Argument 1 to "Reference" has incompatible type "str"; expected "LocatableString"
src/inmanta/ast/variables.py:78: error: Argument 2 to "AttributeReference" has incompatible type "str"; expected "LocatableString"
src/inmanta/ast/variables.py:126: error: Incompatible return value type (got "Union[Type, ResultVariable[Any]]", expected "ResultVariable[Any]")
src/inmanta/ast/variables.py:155: error: Argument 4 to "RawUnit" has incompatible type "AbstractAttributeReferenceHelper[T]"; expected "RawResumer"
src/inmanta/ast/variables.py:215: error: Argument 2 to "__init__" of "Reference" has incompatible type "str"; expected "LocatableString"
src/inmanta/ast/variables.py:231: error: Need type annotation for 'temp'
src/inmanta/ast/variables.py:239: error: Argument 4 to "RawUnit" has incompatible type "AttributeReferenceHelper"; expected "RawResumer"
src/inmanta/ast/variables.py:250: error: Argument 2 to "AttributeReference" has incompatible type "str"; expected "LocatableString"
src/inmanta/agent/io/remote.py:24: error: Cannot find module named 'execnet'
src/inmanta/agent/io/remote.py:24: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
src/inmanta/agent/io/remote.py:93: error: Argument "hostname" to "HostNotFoundException" has incompatible type "Optional[str]"; expected "str"
src/inmanta/agent/io/remote.py:103: error: Argument "hostname" to "HostNotFoundException" has incompatible type "Optional[str]"; expected "str"
src/inmanta/agent/io/remote.py:103: error: Argument "error" to "HostNotFoundException" has incompatible type "BrokenPipeError"; expected "str"
src/inmanta/ast/statements/generator.py:92: error: "Resolver" has no attribute "add_implementation"
src/inmanta/ast/statements/generator.py:150: error: "BasicBlock" has no attribute "requires"
src/inmanta/ast/statements/generator.py:154: error: Need type annotation for 'target'
src/inmanta/ast/statements/generator.py:156: error: Argument 5 to "ExecutionUnit" has incompatible type "For"; expected "ExpressionStatement"
src/inmanta/ast/statements/generator.py:164: error: Need type annotation for 'helperwrapped'
src/inmanta/ast/statements/generator.py:188: error: "object" has no attribute "receive_result"
src/inmanta/ast/statements/generator.py:266: error: Incompatible types in assignment (expression has type "Type", variable has type "EntityLike")
src/inmanta/ast/statements/generator.py:295: error: "Constructor" has no attribute "get_default_values"
src/inmanta/ast/statements/generator.py:332: error: Argument 2 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"
src/inmanta/ast/statements/generator.py:343: error: Argument 1 to "copy_location" of "Statement" has incompatible type "Instance"; expected "Locatable"
src/inmanta/ast/statements/generator.py:366: error: Argument 1 to "append" of "list" has incompatible type "Optional[Tracker]"; expected "Tracker"
src/inmanta/ast/statements/call.py:124: error: Argument 1 to "set_provider" of "ResultVariable" has incompatible type "FunctionUnit"; expected "Statement"
src/inmanta/ast/constraint/expression.py:70: error: Argument 1 to "__init__" of "ReferenceStatement" has incompatible type "List[Reference]"; expected "List[ExpressionStatement]"
src/inmanta/ast/constraint/expression.py:70: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
src/inmanta/ast/constraint/expression.py:70: note: Consider using "Sequence" instead, which is covariant
src/inmanta/ast/constraint/expression.py:76: error: Need type annotation for 'temp'
src/inmanta/ast/constraint/expression.py:84: error: Argument 4 to "RawUnit" has incompatible type "IsDefinedReferenceHelper"; expected "RawResumer"
src/inmanta/ast/constraint/expression.py:107: error: Need type annotation for '__operator' (hint: "__operator: Dict[<type>, <type>] = ...")
src/inmanta/parser/plyInmantaLex.py:67: error: Argument 1 to "get" of "Mapping" has incompatible type "Union[str, LocatableString]"; expected "str"
src/inmanta/parser/plyInmantaLex.py:68: error: Value of type "Union[str, LocatableString]" is not indexable
src/inmanta/parser/plyInmantaLex.py:76: error: Argument 1 to "LocatableString" has incompatible type "Union[str, LocatableString]"; expected "str"
src/inmanta/parser/plyInmantaLex.py:136: error: Value of type "Union[str, LocatableString]" is not indexable
src/inmanta/parser/plyInmantaLex.py:158: error: Incompatible types in assignment (expression has type "float", variable has type "Union[str, LocatableString]")
src/inmanta/parser/plyInmantaLex.py:158: error: Argument 1 to "float" has incompatible type "Union[str, LocatableString]"; expected "Union[SupportsFloat, str, bytes, bytearray]"
src/inmanta/parser/plyInmantaLex.py:164: error: Incompatible types in assignment (expression has type "int", variable has type "Union[str, LocatableString]")
src/inmanta/parser/plyInmantaLex.py:164: error: Argument 1 to "int" has incompatible type "Union[str, LocatableString]"; expected "Union[str, bytes, SupportsInt]"
src/inmanta/parser/plyInmantaLex.py:177: error: Value of type "Union[str, LocatableString]" is not indexable
src/inmanta/parser/plyInmantaLex.py:193: error: Argument 1 to "Reference" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaLex.py:194: error: Value of type "Union[str, LocatableString]" is not indexable
src/inmanta/parser/plyInmantaLex.py:195: error: Incompatible types in assignment (expression has type "Regex", variable has type "Union[str, LocatableString]")
src/inmanta/parser/plyInmantaLex.py:202: error: Argument 1 to "len" has incompatible type "Union[str, LocatableString]"; expected "Sized"
src/inmanta/parser/plyInmantaLex.py:208: error: Argument 1 to "len" has incompatible type "Union[str, LocatableString]"; expected "Sized"
src/inmanta/parser/plyInmantaLex.py:223: error: Argument 1 to "len" has incompatible type "Union[str, LocatableString]"; expected "Sized"
src/inmanta/parser/plyInmantaLex.py:224: error: Value of type "Union[str, LocatableString]" is not indexable
src/inmanta/parser/plyInmantaLex.py:234: error: Argument 1 to "ParserException" has incompatible type "str"; expected "Range"
src/inmanta/ast/entity.py:159: error: Incompatible return value type (got "Dict[str, object]", expected "Dict[str, ExpressionStatement]")
src/inmanta/ast/entity.py:203: error: Incompatible types in assignment (expression has type "property", variable has type "Dict[str, Attribute]")
src/inmanta/ast/entity.py:264: error: Incompatible return value type (got "None", expected "Attribute")
src/inmanta/ast/entity.py:297: error: Incompatible return value type (got "None", expected "Attribute")
src/inmanta/ast/entity.py:348: error: Return type "bool" of "validate" incompatible with return type "None" in supertype "Type"
src/inmanta/ast/entity.py:440: error: Argument 1 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"
src/inmanta/ast/entity.py:440: error: Argument 2 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"
src/inmanta/ast/entity.py:450: error: "list" expects 1 type argument, but 2 given
src/inmanta/ast/entity.py:560: error: Incompatible types in assignment (expression has type "None", variable has type "ExpressionStatement")
src/inmanta/ast/entity.py:581: error: Incompatible types in assignment (expression has type "None", variable has type "Entity")
src/inmanta/ast/entity.py:589: error: Incompatible types in assignment (expression has type "EntityLike", variable has type "Entity")
src/inmanta/ast/entity.py:590: error: List item 0 has incompatible type "EntityLike"; expected "Entity"
src/inmanta/ast/entity.py:605: error: "Default" has no attribute "_entity"; maybe "entity", "set_entity", or "get_entity"?
src/inmanta/ast/entity.py:606: error: "Default" has no attribute "_entity"; maybe "entity", "set_entity", or "get_entity"?
src/inmanta/ast/entity.py:632: error: "Default" has no attribute "__name"; maybe "name"?
src/inmanta/ast/statements/define.py:423: error: Incompatible types in assignment (expression has type "property", variable has type "ExpressionStatement")
src/inmanta/ast/statements/define.py:573: error: Argument 1 to "set_multiplicity" of "RelationAttribute" has incompatible type "Tuple[Optional[int], Optional[int]]"; expected "Tuple[int, int]"
src/inmanta/ast/statements/define.py:586: error: Argument 1 to "set_multiplicity" of "RelationAttribute" has incompatible type "Tuple[Optional[int], Optional[int]]"; expected "Tuple[int, int]"
src/inmanta/ast/statements/define.py:688: error: Return type "None" of "register_types" incompatible with return type "Tuple[str, NamedType]" in supertype "TypeDefinitionStatement"
src/inmanta/ast/statements/define.py:689: error: Incompatible types in assignment (expression has type "Optional[Namespace]", variable has type "Namespace")
src/inmanta/parser/plyInmantaParser.py:85: error: Argument 4 to "LocatableString" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:97: error: Incompatible types in assignment (expression has type "None", variable has type "Namespace")
src/inmanta/parser/plyInmantaParser.py:98: error: "Literal" has no attribute "lexpos"
src/inmanta/parser/plyInmantaParser.py:134: error: Argument 1 to "DefineImport" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaParser.py:134: error: Argument 2 to "DefineImport" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaParser.py:140: error: Argument 1 to "DefineImport" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaParser.py:193: error: Argument 1 to "BasicBlock" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:199: error: Argument 1 to "BasicBlock" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:205: error: Argument 1 to "BasicBlock" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:216: error: Argument 1 to "DefineEntity" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:227: error: Argument 1 to "DefineEntity" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:415: error: Argument 1 to "DefineImplementation" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:415: error: Argument 1 to "BasicBlock" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:465: error: Incompatible types in assignment (expression has type "str", variable has type "None")
src/inmanta/parser/plyInmantaParser.py:490: error: Argument 1 to "DefineRelation" has incompatible type "Tuple[Any, None, None]"; expected "Tuple[LocatableString, LocatableString, Tuple[Optional[int], Optional[int]]]"
src/inmanta/parser/plyInmantaParser.py:502: error: Argument 1 to "DefineRelation" has incompatible type "Tuple[Any, None, None]"; expected "Tuple[LocatableString, LocatableString, Tuple[Optional[int], Optional[int]]]"
src/inmanta/parser/plyInmantaParser.py:544: error: Argument 1 to "DefineTypeConstraint" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:550: error: Argument 1 to "DefineTypeDefault" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:640: error: Argument 4 to "Constructor" has incompatible type "None"; expected "Namespace"
src/inmanta/parser/plyInmantaParser.py:766: error: Argument 1 to "Reference" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaParser.py:767: error: Incompatible types in assignment (expression has type "None", variable has type "Namespace")
src/inmanta/parser/plyInmantaParser.py:771: error: Argument 2 to "AttributeReference" has incompatible type "str"; expected "LocatableString"
src/inmanta/parser/plyInmantaParser.py:773: error: Incompatible types in assignment (expression has type "None", variable has type "Namespace")
src/inmanta/parser/plyInmantaParser.py:959: error: "str" has no attribute "location"
src/inmanta/module.py:53: error: No library stub file for module 'pkg_resources.packaging.version'
src/inmanta/module.py:550: error: Argument 3 to "ModuleNotFoundException" has incompatible type "InvalidModuleException"; expected "RuntimeException"
src/inmanta/module.py:762: error: Incompatible return value type (got "None", expected "str")
src/inmanta/module.py:773: error: Incompatible return value type (got "None", expected "str")
src/inmanta/module.py:785: error: Incompatible return value type (got "None", expected "str")
src/inmanta/module.py:807: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"
src/inmanta/module.py:808: error: Argument 2 to "clone" of "CompositeModuleRepo" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:832: error: Argument 1 to "fetch" of "CLIGitProvider" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:835: error: Argument 1 to "checkout_tag" of "CLIGitProvider" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:837: error: Argument 1 to "pull" of "CLIGitProvider" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:840: error: Argument 3 to "get_suitable_version_for" of "Module" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:845: error: Argument 1 to "checkout_tag" of "CLIGitProvider" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:847: error: Argument 2 to "Module" has incompatible type "Optional[str]"; expected "str"
src/inmanta/module.py:865: error: "Requirement" has no attribute "specifier"
src/inmanta/module.py:869: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Optional[str]")
src/inmanta/module.py:871: error: Incompatible types in assignment (expression has type "Tuple[str, ...]", variable has type "Optional[str]")
src/inmanta/module.py:871: error: "str" has no attribute "base_version"
src/inmanta/module.py:886: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
src/inmanta/module.py:1000: error: Need type annotation for 'out' (hint: "out: Dict[<type>, <type>] = ...")
src/inmanta/module.py:1026: error: Need type annotation for 'files' (hint: "files: List[<type>] = ...")
src/inmanta/loader.py:176: error: "Type[WorkingSet]" has no attribute "_build_master"
src/inmanta/loader.py:233: error: "Type[WorkingSet]" has no attribute "_build_master"
src/inmanta/agent/agent.py:338: error: Argument 2 to "__init__" of "ResourceAction" has incompatible type "None"; expected "Resource"
src/inmanta/agent/agent.py:491: error: Attribute 'generation' already defined on line 415
src/inmanta/agent/agent.py:509: error: Argument 2 to "ResourceAction" has incompatible type "None"; expected "Resource"
src/inmanta/agent/agent.py:513: error: Argument 2 to "execute" of "ResourceAction" has incompatible type "Dict[str, ResourceAction]"; expected "Dict[ResourceIdStr, ResourceAction]"
src/inmanta/export.py:147: error: Incompatible types in assignment (expression has type "List[Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]]", target has type "Dict[str, Sequence[Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]]]")
src/inmanta/export.py:149: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "Dict[str, Sequence[Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]]]")
src/inmanta/export.py:169: error: Argument 3 to "create_from_model" of "Resource" has incompatible type "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]"; expected "DynamicProxy"
src/inmanta/export.py:211: error: Unexpected keyword argument "types"
src/inmanta/export.py:213: error: Too few arguments
src/inmanta/export.py:329: error: Argument 1 to "json_encode" has incompatible type "List[Dict[str, Any]]"; expected "Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]], Mapping[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]], None]"
src/inmanta/export.py:331: error: Argument 1 to "ModelExporter" has incompatible type "Optional[Dict[str, Entity]]"; expected "Dict[str, Entity]"
src/inmanta/export.py:339: error: Argument 4 to "commit_resources" of "Exporter" has incompatible type "Optional[Dict[str, Any]]"; expected "Dict[Any, Any]"
src/inmanta/export.py:343: error: No return value expected
src/inmanta/export.py:344: error: No return value expected
src/inmanta/export.py:368: error: Argument 1 to "add" of "set" has incompatible type "Optional[str]"; expected "str"
src/inmanta/export.py:417: error: Argument 1 to "deploy_code" of "Exporter" has incompatible type "SyncClient"; expected "Client"
src/inmanta/export.py:514: error: Argument 2 to "add" of "Exporter" has incompatible type "Tuple[str, ...]"; expected "List[str]"
src/inmanta/export.py:526: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:526: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:526: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:526: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:526: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:526: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "path"
src/inmanta/export.py:526: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "path"
src/inmanta/export.py:526: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "path"
src/inmanta/export.py:526: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "path"
src/inmanta/export.py:526: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "path"
src/inmanta/export.py:528: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:528: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:528: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:528: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:528: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:531: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:531: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:531: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:531: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:531: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "content"
src/inmanta/export.py:536: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:536: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:536: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:536: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:536: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:536: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:536: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:536: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:536: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:536: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:541: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:541: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:541: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:541: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:541: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "host"
src/inmanta/export.py:541: error: Item "str" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:541: error: Item "Tuple[Any, ...]" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:541: error: Item "int" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:541: error: Item "float" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:541: error: Item "bool" of "Union[str, Tuple[Any, ...], int, float, bool, DynamicProxy]" has no attribute "name"
src/inmanta/export.py:587: error: "Type" has no attribute "get_full_name"
src/inmanta/export.py:589: error: Argument 1 to "relation_name" has incompatible type "Type"; expected "Entity"
src/inmanta/export.py:589: error: Argument 2 to "relation_name" has incompatible type "Optional[RelationAttribute]"; expected "RelationAttribute"
src/inmanta/export.py:652: error: Need type annotation for 'unknowns' (hint: "unknowns: List[<type>] = ...")
src/inmanta/protocol/rest/server.py:26: error: Module 'pyformance' has no attribute 'timer'
src/inmanta/protocol/rest/server.py:274: error: Argument 1 to "Application" has incompatible type "List[Rule]"; expected "Optional[List[Union[Rule, List[Any], Tuple[Union[str, Matcher], Any], Tuple[Union[str, Matcher], Any, Dict[str, Any]], Tuple[Union[str, Matcher], Any, Dict[str, Any], str]]]]"
src/inmanta/protocol/rest/server.py:274: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
src/inmanta/protocol/rest/server.py:274: note: Consider using "Sequence" instead, which is covariant
src/inmanta/protocol/rest/server.py:281: error: Argument 1 to "load_cert_chain" of "SSLContext" has incompatible type "Union[str, ConfigParser]"; expected "str"
src/inmanta/protocol/rest/server.py:281: error: Argument 2 to "load_cert_chain" of "SSLContext" has incompatible type "Union[str, ConfigParser]"; expected "Optional[str]"
src/inmanta/moduletool.py:29: error: Cannot find module named 'texttable'
src/inmanta/moduletool.py:310: error: Incompatible types in assignment (expression has type Module, variable has type "Optional[str]")
src/inmanta/moduletool.py:311: error: Incompatible return value type (got "None", expected Module)
src/inmanta/main.py:29: error: Cannot find module named 'texttable'
src/inmanta/main.py:562: error: Value of type "object" is not indexable
src/inmanta/main.py:598: error: Value of type "Optional[Dict[str, Any]]" is not indexable
src/inmanta/main.py:607: error: Argument 1 to "parse_id" of "Id" has incompatible type "str"; expected "Union[ResourceVersionIdStr, ResourceIdStr]"
src/inmanta/main.py:607: error: Invalid index type "str" for "str"; expected type "Union[int, slice]"
src/inmanta/main.py:618: error: Value of type "Optional[Dict[str, Any]]" is not indexable
src/inmanta/main.py:632: error: Value of type "Optional[Dict[str, Any]]" is not indexable
src/inmanta/main.py:673: error: "str" has no attribute "items"
src/inmanta/main.py:704: error: Need type annotation for 'data' (hint: "data: Dict[<type>, <type>] = ...")
src/inmanta/main.py:747: error: Need type annotation for 'fields' (hint: "fields: List[<type>] = ...")
src/inmanta/main.py:750: error: "str" has no attribute "keys"
src/inmanta/main.py:752: error: "str" has no attribute "values"
src/inmanta/main.py:785: error: Incompatible types in assignment (expression has type "List[Dict[str, str]]", variable has type "Dict[str, str]")
src/inmanta/main.py:785: error: No overload variant of "__getitem__" of "list" matches argument type "str"
src/inmanta/main.py:785: note: Possible overload variants:
src/inmanta/main.py:785: note:     def __getitem__(self, int) -> Dict[str, str]
src/inmanta/main.py:785: note:     def __getitem__(self, slice) -> List[Dict[str, str]]
src/inmanta/db/migrate_to_postgresql.py:23: error: No library stub file for module 'pymongo'
src/inmanta/compiler/help/explainer.py:119: error: "CompilerException" has no attribute "attribute"
src/inmanta/compiler/help/explainer.py:120: error: "CompilerException" has no attribute "instance"
src/inmanta/compiler/help/explainer.py:121: error: "CompilerException" has no attribute "resultvariable"
src/inmanta/compiler/help/explainer.py:122: error: "CompilerException" has no attribute "value"
src/inmanta/compiler/help/explainer.py:124: error: "CompilerException" has no attribute "reverse"
src/inmanta/compiler/help/explainer.py:125: error: "CompilerException" has no attribute "reverse"
src/inmanta/compiler/help/explainer.py:126: error: "CompilerException" has no attribute "resultvariable"
src/inmanta/server/protocol.py:68: error: Argument "timeout" to "put_call" of "Session" has incompatible type "Optional[int]"; expected "int"
src/inmanta/server/protocol.py:81: error: Incompatible types in assignment (expression has type "None", variable has type "List[ServerSlice]")
src/inmanta/server/protocol.py:83: error: Incompatible types in assignment (expression has type "Union[str, ConfigParser]", variable has type "Optional[str]")
src/inmanta/server/protocol.py:88: error: Argument 1 to "RESTServer" has incompatible type "SessionManager"; expected "SessionManagerInterface"
src/inmanta/server/protocol.py:97: error: Incompatible types in assignment (expression has type "None", variable has type "List[ServerSlice]")
src/inmanta/server/protocol.py:308: error: Argument 1 to "append" of "list" has incompatible type "Tuple[str, Type[RedirectHandler], Dict[str, str]]"; expected "Rule"
src/inmanta/server/protocol.py:366: error: Incompatible types in assignment (expression has type "object", variable has type "None")
src/inmanta/server/protocol.py:397: error: Need type annotation for 'future'
src/inmanta/server/protocol.py:483: error: Argument 1 to "start" of "RESTServer" has incompatible type "ValuesView[ServerSlice]"; expected "List[CallTarget]"
src/inmanta/server/protocol.py:504: error: Item "None" of "Optional[HTTPServer]" has no attribute "_sockets"
src/inmanta/server/protocol.py:600: error: Dict entry 0 has incompatible type "str": "List[Request]"; expected "str": "str"
src/inmanta/server/services/metricservice.py:51: error: Argument "tags" to "InfluxReporter" has incompatible type "Collection[str]"; expected "Dict[str, str]"
src/inmanta/server/services/databaseservice.py:90: error: Incompatible return value type (got "Dict[str, object]", expected "Dict[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]], Mapping[str, Union[BaseModel, Enum, UUID, StrictNonIntBool, int, float, datetime, str]]]]")
src/inmanta/server/services/compilerservice.py:248: error: Argument 3 to "get" of "Config" has incompatible type "bool"; expected "Optional[str]"
src/inmanta/server/services/compilerservice.py:353: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "bool")
src/inmanta/server/services/compilerservice.py:481: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[CompilerService, Environment], Coroutine[Any, Any, List[CompileRun]]]"
src/inmanta/server/services/compilerservice.py:487: error: List comprehension has incompatible type List[inmanta.data.model.CompileRun]; expected List[inmanta.server.services.compilerservice.CompileRun]
src/inmanta/server/server.py:23: error: Cannot find module named 'importlib_metadata'
src/inmanta/server/bootloader.py:39: error: Module has no attribute "__path__"
src/inmanta/server/bootloader.py:127: error: Module has no attribute "setup"
src/inmanta/server/agentmanager.py:248: error: "List[AgentProcess]" has no attribute "update_fields"
src/inmanta/server/agentmanager.py:250: error: "List[AgentProcess]" has no attribute "sid"
src/inmanta/server/agentmanager.py:290: error: "List[AgentProcess]" has no attribute "update_fields"
src/inmanta/server/agentmanager.py:467: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "Dict[str, str]")
src/inmanta/server/agentmanager.py:491: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "Dict[str, str]")
src/inmanta/server/agentmanager.py:537: error: Argument 1 to "join" has incompatible type "Union[str, ConfigParser]"; expected "Union[str, _PathLike[str]]"
src/inmanta/server/agentmanager.py:539: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "int")
src/inmanta/server/agentmanager.py:540: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "int")
src/inmanta/server/agentmanager.py:542: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "int")
src/inmanta/server/agentmanager.py:543: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "int")
src/inmanta/app.py:48: error: Cannot find module named 'colorlog'
src/inmanta/app.py:83: error: Argument 2 to "safe_shutdown" has incompatible type "Callable[[], Coroutine[Any, Any, None]]"; expected "Callable[[], None]"
src/inmanta/app.py:89: error: Argument 2 to "safe_shutdown" has incompatible type "Callable[[], Coroutine[Any, Any, None]]"; expected "Callable[[], None]"
src/inmanta/app.py:116: error: Invalid index type "Optional[int]" for "Dict[int, Any]"; expected type "int"
src/inmanta/app.py:253: error: "runctx" does not return a value
src/inmanta/app.py:441: error: "run" of "Exporter" does not return a value
src/inmanta/app.py:617: error: Argument 1 to "excepthook" has incompatible type "*Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]"; expected "Type[BaseException]"
src/inmanta/app.py:617: error: Argument 1 to "excepthook" has incompatible type "*Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]"; expected "BaseException"
src/inmanta/app.py:617: error: Argument 1 to "excepthook" has incompatible type "*Tuple[Optional[Type[BaseException]], Optional[BaseException], Optional[TracebackType]]"; expected "TracebackType"
src/inmanta/app.py:635: error: Argument 1 to "report" has incompatible type "KeyboardInterrupt"; expected "Exception"
src/inmanta/server/services/resourceservice.py:57: error: Argument "level" to "__init__" of "LogRecord" has incompatible type "str"; expected "int"
src/inmanta/server/services/resourceservice.py:57: error: Argument "args" to "__init__" of "LogRecord" has incompatible type "List[<nothing>]"; expected "Union[Tuple[Any, ...], Mapping[str, Any]]"
src/inmanta/server/services/resourceservice.py:69: error: Incompatible types in assignment (expression has type "float", variable has type "int")
src/inmanta/server/services/resourceservice.py:71: error: Module has no attribute "_startTime"
src/inmanta/server/services/resourceservice.py:109: error: Incompatible types in assignment (expression has type "None", target has type "Tuple[Set[ResourceVersionIdStr], List[ResourceVersionIdStr]]")
src/inmanta/server/services/resourceservice.py:180: error: Argument 2 to "ResourceActionLogLine" has incompatible type "int"; expected "str"
src/inmanta/server/services/paramservice.py:229: error: "Sequence[str]" has no attribute "append"
src/inmanta/server/services/dryrunservice.py:128: error: Incompatible types in assignment (expression has type "int", target has type "UUID")
src/inmanta/server/services/dryrunservice.py:130: error: Argument 1 to "get_list" of "BaseDocument" has incompatible type "**Dict[str, UUID]"; expected "Optional[str]"
src/inmanta/server/services/dryrunservice.py:130: error: Argument 1 to "get_list" of "BaseDocument" has incompatible type "**Dict[str, UUID]"; expected "str"
src/inmanta/server/services/dryrunservice.py:130: error: Argument 1 to "get_list" of "BaseDocument" has incompatible type "**Dict[str, UUID]"; expected "Optional[int]"
src/inmanta/server/services/dryrunservice.py:130: error: Argument 1 to "get_list" of "BaseDocument" has incompatible type "**Dict[str, UUID]"; expected "bool"
src/inmanta/server/services/dryrunservice.py:148: error: Argument 1 to "parse_id" of "Id" has incompatible type "str"; expected "Union[ResourceVersionIdStr, ResourceIdStr]"
src/inmanta/server/services/orchestrationservice.py:96: error: Argument 3 to "get_versions" of "ConfigurationModel" has incompatible type "Optional[int]"; expected "int"
src/inmanta/server/services/orchestrationservice.py:102: error: Incompatible types in assignment (expression has type "int", target has type "List[ConfigurationModel]")
src/inmanta/server/services/orchestrationservice.py:103: error: Incompatible types in assignment (expression has type "Optional[int]", target has type "List[ConfigurationModel]")
src/inmanta/server/services/orchestrationservice.py:105: error: Incompatible types in assignment (expression has type "int", target has type "List[ConfigurationModel]")
src/inmanta/server/services/orchestrationservice.py:129: error: Incompatible types in assignment (expression has type "List[<nothing>]", target has type "ConfigurationModel")
src/inmanta/server/services/orchestrationservice.py:132: error: Argument 4 to "get_log" of "ResourceAction" has incompatible type "Optional[int]"; expected "int"
src/inmanta/server/services/orchestrationservice.py:133: error: Value of type "Resource" is not indexable
src/inmanta/server/services/orchestrationservice.py:138: error: Incompatible types in assignment (expression has type "List[UnknownParameter]", target has type "ConfigurationModel")
src/inmanta/server/services/orchestrationservice.py:207: error: Invalid index type "ResourceVersionIdStr" for "Dict[ResourceIdStr, ResourceState]"; expected type "ResourceIdStr"
src/inmanta/server/services/orchestrationservice.py:240: error: Invalid index type "ResourceIdStr" for "Dict[ResourceVersionIdStr, Resource]"; expected type "ResourceVersionIdStr"
src/inmanta/server/services/orchestrationservice.py:286: error: Invalid index type "ResourceIdStr" for "Dict[ResourceVersionIdStr, Resource]"; expected type "ResourceVersionIdStr"
src/inmanta/server/services/orchestrationservice.py:326: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", target has type "Union[UUID, StrictNonIntBool, int, float, datetime, str]")
src/inmanta/server/services/orchestrationservice.py:361: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "bool")
src/inmanta/server/services/orchestrationservice.py:363: error: Invalid index type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]" for "Type[AgentTriggerMethod]"; expected type "str"
src/inmanta/server/services/orchestrationservice.py:388: error: List comprehension has incompatible type List[str]; expected List[ResourceIdStr]
src/inmanta/server/services/orchestrationservice.py:393: error: Argument 2 to "resource_action_update" of "ResourceService" has incompatible type "List[ResourceIdStr]"; expected "List[ResourceVersionIdStr]"
src/inmanta/server/services/orchestrationservice.py:408: error: List comprehension has incompatible type List[str]; expected List[ResourceIdStr]
src/inmanta/server/services/orchestrationservice.py:410: error: Argument 2 to "resource_action_update" of "ResourceService" has incompatible type "List[ResourceIdStr]"; expected "List[ResourceVersionIdStr]"
Generated HTML report (via XSLT): /home/sander/documents/projects/inmanta/inmanta/mypy/index.html
