stubs/graphviz/files.pyi:5: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:5: note: Use "-> None" if function does not return a value
stubs/graphviz/files.pyi:9: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:9: note: Use "-> None" if function does not return a value
stubs/graphviz/files.pyi:13: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:13: note: Use "-> None" if function does not return a value
stubs/graphviz/files.pyi:16: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:16: note: Use "-> None" if function does not return a value
stubs/graphviz/files.pyi:25: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:26: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:28: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:28: note: Use "-> None" if function does not return a value
stubs/graphviz/files.pyi:29: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:30: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/files.pyi:35: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/stable_api.py:20: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/stable_api.py:20: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/parser/parsetab.py:9265: error: Need type annotation for "_lr_action" (hint: "_lr_action: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/parser/parsetab.py:11158: error: Need type annotation for "_lr_goto" (hint: "_lr_goto: Dict[<type>, <type>] = ...")  [var-annotated]
stubs/pyformance/__init__.pyi:7: error: Function is missing a type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:16: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:16: note: Use "-> None" if function does not return a value
stubs/graphviz/dot.pyi:21: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:27: error: Function is missing a type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:32: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:32: note: Use "-> None" if function does not return a value
stubs/graphviz/dot.pyi:36: error: Function is missing a return type annotation  [no-untyped-def]
stubs/graphviz/dot.pyi:36: note: Use "-> None" if function does not return a value
src/inmanta/agent/io/local.py:29: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
src/inmanta/agent/io/local.py:30: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
src/inmanta/agent/io/local.py:36: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[str], struct_passwd]")  [assignment]
src/inmanta/agent/io/local.py:41: error: Incompatible types in assignment (expression has type "None", variable has type "Callable[[str], struct_group]")  [assignment]
src/inmanta/agent/io/local.py:99: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/io/local.py:122: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:145: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:158: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:181: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:197: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:210: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:223: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:236: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:253: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:267: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
src/inmanta/agent/io/local.py:269: error: Incompatible return value type (got "Dict[str, str]", expected "Dict[str, Union[str, int]]")  [return-value]
src/inmanta/agent/io/local.py:269: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/agent/io/local.py:269: note: Consider using "Mapping" instead, which is covariant in the value type
src/inmanta/agent/io/local.py:269: note: Perhaps you need a type annotation for "status"? Suggestion: "Dict[str, Union[str, int]]"
src/inmanta/agent/io/local.py:276: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:288: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:290: error: Argument "input" to "communicate" of "Popen" has incompatible type "str"; expected "Optional[bytes]"  [arg-type]
src/inmanta/agent/io/local.py:314: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:325: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:335: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:351: error: Call to untyped function "_run_as_args" in typed context  [no-untyped-call]
src/inmanta/agent/io/local.py:452: error: Incompatible types in assignment (expression has type "Dict[bytes, bytes]", variable has type "Dict[str, str]")  [assignment]
src/inmanta/agent/io/local.py:521: error: Incompatible types in assignment (expression has type "int", target has type "str")  [assignment]
src/inmanta/agent/io/local.py:523: error: Incompatible return value type (got "Dict[str, str]", expected "Dict[str, Union[int, str]]")  [return-value]
src/inmanta/agent/io/local.py:523: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/agent/io/local.py:523: note: Consider using "Mapping" instead, which is covariant in the value type
src/inmanta/agent/io/local.py:523: note: Perhaps you need a type annotation for "status"? Suggestion: "Dict[str, Union[int, str]]"
src/inmanta/agent/io/local.py:543: error: Argument 1 to "write" of "BufferedWriter" has incompatible type "str"; expected "Union[bytes, Union[bytearray, memoryview, array[Any], mmap, _CData, PickleBuffer]]"  [arg-type]
src/inmanta/agent/io/local.py:591: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")  [assignment]
src/inmanta/agent/io/local.py:594: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "Optional[str]")  [assignment]
src/inmanta/agent/io/local.py:599: error: Incompatible types in assignment (expression has type "int", variable has type "Optional[str]")  [assignment]
src/inmanta/agent/io/local.py:601: error: Incompatible types in assignment (expression has type "Optional[int]", variable has type "Optional[str]")  [assignment]
src/inmanta/agent/io/local.py:605: error: Argument 2 to "chown" has incompatible type "Optional[str]"; expected "int"  [arg-type]
src/inmanta/agent/io/local.py:605: error: Argument 3 to "chown" has incompatible type "Optional[str]"; expected "int"  [arg-type]
src/inmanta/agent/io/local.py:644: error: Name "channel" is not defined  [name-defined]
src/inmanta/agent/io/local.py:649: error: Name "channel" is not defined  [name-defined]
src/inmanta/agent/io/local.py:653: error: Name "channel" is not defined  [name-defined]
src/inmanta/db/versions/v202109100.py:51: error: Need type annotation for "message"  [var-annotated]
src/inmanta/db/versions/v202109100.py:51: error: Argument 1 to "enumerate" has incompatible type "object"; expected "Iterable[<nothing>]"  [arg-type]
src/inmanta/db/versions/v202109100.py:55: error: Unsupported target for indexed assignment ("object")  [index]
src/inmanta/warnings.py:51: error: Argument 1 to "filterwarnings" has incompatible type "str"; expected "Literal['default', 'error', 'ignore', 'always', 'module', 'once']"  [arg-type]
src/inmanta/warnings.py:121: error: Argument 1 to "filterwarnings" has incompatible type "str"; expected "Literal['default', 'error', 'ignore', 'always', 'module', 'once']"  [arg-type]
src/inmanta/warnings.py:123: error: Argument 1 to "filterwarnings" has incompatible type "str"; expected "Literal['default', 'error', 'ignore', 'always', 'module', 'once']"  [arg-type]
src/inmanta/warnings.py:154: error: Unused "type: ignore" comment
src/inmanta/docstring_parser.py:40: error: Value expression in dictionary comprehension has incompatible type "Optional[str]"; expected type "str"  [misc]
src/inmanta/docstring_parser.py:71: error: Incompatible types in assignment (expression has type "Docstring", variable has type "str")  [assignment]
src/inmanta/docstring_parser.py:72: error: Argument 1 to "DocString" has incompatible type "str"; expected "Docstring"  [arg-type]
src/inmanta/data/schema.py:236: error: Incompatible return value type (got "object", expected "int")  [return-value]
src/inmanta/data/schema.py:253: error: Returning Any from function declared to return "Set[int]"  [no-any-return]
src/inmanta/data/schema.py:253: error: No overload variant of "set" matches argument type "object"  [call-overload]
src/inmanta/data/schema.py:253: note: Possible overload variants:
src/inmanta/data/schema.py:253: note:     def [_T] __init__(self) -> Set[_T]
src/inmanta/data/schema.py:253: note:     def [_T] __init__(self, Iterable[_T]) -> Set[_T]
src/inmanta/data/schema.py:282: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/types.py:41: error: Name "types.CallableGenerator" is not defined  [name-defined]
src/inmanta/types.py:63: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/execute/dataflow/__init__.py:331: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/dataflow/__init__.py:608: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/dataflow/__init__.py:622: error: Missing type parameters for generic type "Assignment"  [type-arg]
src/inmanta/execute/dataflow/__init__.py:671: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/__init__.py:244: error: Returning Any from function declared to return "Location"  [no-any-return]
src/inmanta/ast/__init__.py:244: error: "Type" has no attribute "get_entity"  [attr-defined]
src/inmanta/ast/__init__.py:290: error: Attribute "visible_namespaces" already defined on line 287  [no-redef]
src/inmanta/ast/__init__.py:324: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/__init__.py:500: error: Returning Any from function declared to return "Location"  [no-any-return]
src/inmanta/ast/__init__.py:617: error: Argument 2 to "__init__" of "CompilerRuntimeWarning" has incompatible type "LocatableString"; expected "Optional[Locatable]"  [arg-type]
src/inmanta/ast/__init__.py:664: error: Argument 1 to "format_exception_only" has incompatible type "Union[Type[BaseException], Type[None]]"; expected "Optional[Type[BaseException]]"  [arg-type]
src/inmanta/ast/__init__.py:735: error: Argument 2 to "__init__" of "RuntimeException" has incompatible type "Instance"; expected "Optional[Locatable]"  [arg-type]
src/inmanta/ast/__init__.py:807: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/__init__.py:809: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/__init__.py:827: error: Missing type parameters for generic type "DelayedResultVariable"  [type-arg]
src/inmanta/ast/__init__.py:873: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/agent/reporting.py:29: error: Incompatible types in assignment (expression has type "None", variable has type Module)  [assignment]
src/inmanta/agent/reporting.py:75: error: Cannot find implementation or library stub for module named "netifaces"  [import]
src/inmanta/model.py:106: error: No return value expected  [return-value]
src/inmanta/model.py:116: error: Value expression in dictionary comprehension has incompatible type "None"; expected type "Attribute"  [misc]
src/inmanta/model.py:116: error: "List[Dict[str, Any]]" has no attribute "items"  [attr-defined]
src/inmanta/model.py:165: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/model.py:181: error: Call to untyped function "ReferenceValue" in typed context  [no-untyped-call]
src/inmanta/model.py:242: error: "Value" has no attribute "to_dict"  [attr-defined]
src/inmanta/model.py:243: error: "Value" has no attribute "to_dict"  [attr-defined]
src/inmanta/ast/type.py:48: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/type.py:51: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/type.py:58: error: Argument 1 to "TypeNotFoundException" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/ast/type.py:68: error: Argument 1 to "TypeNotFoundException" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/ast/type.py:72: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/type.py:75: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/type.py:78: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/type.py:79: error: Call to untyped function "NameSpacedResolver" in typed context  [no-untyped-call]
src/inmanta/ast/type.py:238: error: List item 0 has incompatible type "Type[int]"; expected "Callable[[object], Number]"  [list-item]
src/inmanta/ast/type.py:238: error: List item 1 has incompatible type "Type[float]"; expected "Callable[[object], Number]"  [list-item]
src/inmanta/ast/type.py:257: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:274: error: Incompatible types in assignment (expression has type "Sequence[Callable[[Optional[object]], object]]", base class "Number" defined the type as "Sequence[Callable[[Optional[object]], Number]]")  [assignment]
src/inmanta/ast/type.py:321: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:363: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:372: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/type.py:372: note: Use "-> None" if function does not return a value
src/inmanta/ast/type.py:391: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:402: error: Call to untyped function "__init__" in typed context  [no-untyped-call]
src/inmanta/ast/type.py:430: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:499: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:529: error: Incompatible return value type (got "None", expected "Location")  [return-value]
src/inmanta/ast/type.py:609: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/ast/type.py:618: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/type.py:645: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/type.py:649: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/ast/type.py:649: error: Call to untyped function "type_string" in typed context  [no-untyped-call]
src/inmanta/ast/type.py:661: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/type.py:668: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/type.py:678: error: Item "Locatable" of "Optional[Locatable]" has no attribute "name"  [union-attr]
src/inmanta/ast/type.py:678: error: Item "None" of "Optional[Locatable]" has no attribute "name"  [union-attr]
src/inmanta/config.py:59: error: Missing type parameters for generic type "Option"  [type-arg]
src/inmanta/config.py:62: error: Missing type parameters for generic type "Option"  [type-arg]
src/inmanta/config.py:103: error: Incompatible return value type (got "Optional[ConfigParser]", expected "ConfigParser")  [return-value]
src/inmanta/config.py:121: error: Overloaded function implementation cannot produce return type of signature 2  [misc]
src/inmanta/config.py:144: error: Incompatible return value type (got "Optional[str]", expected "Union[str, ConfigParser]")  [return-value]
src/inmanta/config.py:145: error: Returning Any from function declared to return "Union[str, ConfigParser]"  [no-any-return]
src/inmanta/config.py:145: error: Argument 1 to "validate" of "Option" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/config.py:157: error: Argument 3 to "validate_option_request" of "Config" has incompatible type "Optional[bool]"; expected "Optional[str]"  [arg-type]
src/inmanta/config.py:158: error: Argument "fallback" to "getboolean" of "RawConfigParser" has incompatible type "Optional[bool]"; expected "bool"  [arg-type]
src/inmanta/config.py:172: error: Missing type parameters for generic type "Option"  [type-arg]
src/inmanta/config.py:176: error: Missing type parameters for generic type "Option"  [type-arg]
src/inmanta/config.py:214: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/config.py:214: error: "ConfigParser" has no attribute "_convert_to_boolean"  [attr-defined]
src/inmanta/config.py:287: error: Incompatible default for argument "validator" (default has type "Callable[[str], str]", argument has type "Callable[[str], T]")  [assignment]
src/inmanta/config.py:288: error: Missing type parameters for generic type "Option"  [type-arg]
src/inmanta/config.py:308: error: Returning Any from function declared to return "T"  [no-any-return]
src/inmanta/config.py:310: error: Argument 1 to "validate" of "Option" has incompatible type "Union[str, T, None]"; expected "str"  [arg-type]
src/inmanta/config.py:451: error: Incompatible types in assignment (expression has type "AuthJWTConfig", variable has type "ConfigParser")  [assignment]
src/inmanta/config.py:452: error: "ConfigParser" has no attribute "sign"  [attr-defined]
src/inmanta/config.py:569: error: Incompatible return value type (got "bytes", expected "str")  [return-value]
src/inmanta/config.py:598: error: "URLError" has no attribute "response"  [attr-defined]
src/inmanta/server/config.py:120: error: Returning Any from function declared to return "int"  [no-any-return]
src/inmanta/server/config.py:120: error: No overload variant of "get" of "Config" matches argument types "str", "str", "int"  [call-overload]
src/inmanta/server/config.py:120: note: Possible overload variants:
src/inmanta/server/config.py:120: note:     def get(cls) -> ConfigParser
src/inmanta/server/config.py:120: note:     def get(cls, section: str, name: str, default_value: Optional[str] = ...) -> Optional[str]
src/inmanta/server/config.py:140: error: Argument 5 to "Option" has incompatible type "Callable[[str], Optional[str]]"; expected "Callable[[str], str]"  [arg-type]
src/inmanta/server/config.py:155: error: No overload variant of "int" matches argument type "object"  [call-overload]
src/inmanta/server/config.py:155: note: Possible overload variants:
src/inmanta/server/config.py:155: note:     def __new__(cls, Union[str, bytes, array[Any], mmap, _CData, PickleBuffer, SupportsInt, SupportsIndex, SupportsTrunc] = ...) -> int
src/inmanta/server/config.py:155: note:     def __new__(cls, Union[str, bytes], base: SupportsIndex) -> int
src/inmanta/server/config.py:162: error: Returning Any from function declared to return "int"  [no-any-return]
src/inmanta/server/config.py:303: error: Argument 3 to "Option" has incompatible type "Callable[[], str]"; expected "Union[int, None, Callable[[], int]]"  [arg-type]
src/inmanta/protocol/decorators.py:51: error: "FuncT" has no attribute "__protocol_method__"  [attr-defined]
src/inmanta/protocol/decorators.py:52: error: "FuncT" has no attribute "__protocol_mapping__"  [attr-defined]
src/inmanta/protocol/decorators.py:53: error: "FuncT" has no attribute "__api_version__"  [attr-defined]
src/inmanta/protocol/decorators.py:75: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/protocol/decorators.py:143: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/execute/runtime.py:182: error: Argument 1 to "ready" of "Waiter" has incompatible type "WrappedValueVariable[T]"; expected "Union[ResultVariable[Any], Waiter]"  [arg-type]
src/inmanta/execute/runtime.py:256: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")  [assignment]
src/inmanta/execute/runtime.py:260: error: Argument 2 to "UnsetException" has incompatible type "ResultVariable[T]"; expected "Optional[Instance]"  [arg-type]
src/inmanta/execute/runtime.py:262: error: Incompatible return value type (got "Optional[T]", expected "T")  [return-value]
src/inmanta/execute/runtime.py:392: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")  [assignment]
src/inmanta/execute/runtime.py:470: error: Incompatible types in assignment (expression has type "None", variable has type "List[Waiter]")  [assignment]
src/inmanta/execute/runtime.py:472: error: Incompatible types in assignment (expression has type "None", variable has type "QueueScheduler")  [assignment]
src/inmanta/execute/runtime.py:515: error: Incompatible types in assignment (expression has type "List[ResultCollector[Union[Instance, List[Instance]]]]", base class "DelayedResultVariable" defined the type as "None")  [assignment]
src/inmanta/execute/runtime.py:531: error: "BaseListVariable" has no attribute "myself"  [attr-defined]
src/inmanta/execute/runtime.py:532: error: "BaseListVariable" has no attribute "attribute"  [attr-defined]
src/inmanta/execute/runtime.py:541: error: "BaseListVariable" has no attribute "myself"  [attr-defined]
src/inmanta/execute/runtime.py:541: error: "BaseListVariable" has no attribute "attribute"  [attr-defined]
src/inmanta/execute/runtime.py:583: error: Missing type parameters for generic type "ResultCollector"  [type-arg]
src/inmanta/execute/runtime.py:664: error: Item "List[Instance]" of "Union[Instance, List[Instance]]" has no attribute "set_attribute"  [union-attr]
src/inmanta/execute/runtime.py:700: error: Incompatible types in assignment (expression has type "Attribute", variable has type "RelationAttribute")  [assignment]
src/inmanta/execute/runtime.py:702: error: Incompatible types in assignment (expression has type "None", variable has type "Location")  [assignment]
src/inmanta/execute/runtime.py:731: error: Incompatible types in assignment (expression has type "object", variable has type "Optional[Instance]")  [assignment]
src/inmanta/execute/runtime.py:748: error: Argument 1 to "get_value" of "ResultVariable" has incompatible type "OptionVariable"; expected "ResultVariable[T]"  [arg-type]
src/inmanta/execute/runtime.py:751: error: Incompatible return value type (got "T", expected "Instance")  [return-value]
src/inmanta/execute/runtime.py:814: error: Missing type parameters for generic type "DelayedResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:846: error: Missing type parameters for generic type "DelayedResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:875: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/runtime.py:883: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:890: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:894: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:922: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/runtime.py:933: error: Argument 1 to "waitfor" of "Waiter" has incompatible type "VariableABC[Any]"; expected "ResultVariable[Any]"  [arg-type]
src/inmanta/execute/runtime.py:969: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/runtime.py:970: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:979: error: Argument 1 to "waitfor" of "Waiter" has incompatible type "VariableABC[Any]"; expected "ResultVariable[Any]"  [arg-type]
src/inmanta/execute/runtime.py:984: error: Argument 4 to "resume" of "Resumer" has incompatible type "Optional[ResultVariable[Any]]"; expected "ResultVariable[Any]"  [arg-type]
src/inmanta/execute/runtime.py:1003: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/runtime.py:1013: error: Argument 1 to "waitfor" of "Waiter" has incompatible type "VariableABC[Any]"; expected "ResultVariable[Any]"  [arg-type]
src/inmanta/execute/runtime.py:1111: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:1127: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:1146: error: Argument 1 to "set_location" of "Locatable" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/execute/runtime.py:1150: error: Argument 1 to "get_location" of "Locatable" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/execute/runtime.py:1172: error: Argument 1 to "__init__" of "Locatable" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/execute/runtime.py:1176: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:1195: error: Argument 2 to "set_value" of "ResultVariable" has incompatible type "None"; expected "Location"  [arg-type]
src/inmanta/execute/runtime.py:1198: error: Argument 2 to "assign" of "AssignableNodeReference" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/execute/runtime.py:1218: error: Argument 1 to "AttributeException" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/execute/runtime.py:1220: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/runtime.py:1243: error: Argument 1 to "RuntimeException" has incompatible type "Instance"; expected "Optional[Locatable]"  [arg-type]
src/inmanta/execute/runtime.py:1284: error: "ResultVariable[Any]" has no attribute "promises"  [attr-defined]
src/inmanta/data/model.py:45: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/data/model.py:45: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/data/model.py:70: error: Missing type parameters for generic type "classmethod"  [type-arg]
src/inmanta/data/model.py:326: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
src/inmanta/data/model.py:328: error: Argument 1 to "ResourceMinimal" has incompatible type "**Dict[str, object]"; expected "ResourceVersionIdStr"  [arg-type]
src/inmanta/data/model.py:344: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/data/model.py:447: error: No overload variant of "StrEnum" matches argument types "str", "List[Tuple[Any, Any]]"  [call-overload]
src/inmanta/data/model.py:447: note: Possible overload variants:
src/inmanta/data/model.py:447: note:     def __new__(cls, object: object = ...) -> StrEnum
src/inmanta/data/model.py:447: note:     def __new__(cls, object: Union[bytes, Union[bytearray, memoryview, array[Any], mmap, _CData, PickleBuffer]], encoding: str = ..., errors: str = ...) -> StrEnum
src/inmanta/data/model.py:448: error: "str" has no attribute "name"  [attr-defined]
src/inmanta/data/model.py:448: error: "str" has no attribute "value"  [attr-defined]
src/inmanta/data/model.py:464: error: Variable "inmanta.data.model.ReleasedResourceState" is not valid as a type  [valid-type]
src/inmanta/data/model.py:464: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src/inmanta/data/model.py:524: error: Variable "inmanta.data.model.ReleasedResourceState" is not valid as a type  [valid-type]
src/inmanta/data/model.py:524: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src/inmanta/data/model.py:525: error: Variable "inmanta.data.model.ReleasedResourceState" is not valid as a type  [valid-type]
src/inmanta/data/model.py:525: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src/inmanta/data/model.py:640: error: No overload variant of "StrEnum" matches argument types "str", "List[Tuple[Any, Any]]"  [call-overload]
src/inmanta/data/model.py:640: note: Possible overload variants:
src/inmanta/data/model.py:640: note:     def __new__(cls, object: object = ...) -> StrEnum
src/inmanta/data/model.py:640: note:     def __new__(cls, object: Union[bytes, Union[bytearray, memoryview, array[Any], mmap, _CData, PickleBuffer]], encoding: str = ..., errors: str = ...) -> StrEnum
src/inmanta/data/model.py:641: error: "str" has no attribute "name"  [attr-defined]
src/inmanta/data/model.py:641: error: "str" has no attribute "value"  [attr-defined]
src/inmanta/data/__init__.py:86: error: Signature of "_generate_next_value_" incompatible with supertype "Enum"  [override]
src/inmanta/data/__init__.py:86: note:      Superclass:
src/inmanta/data/__init__.py:86: note:          @staticmethod
src/inmanta/data/__init__.py:86: note:          def _generate_next_value_(name: str, start: int, count: int, last_values: List[Any]) -> Any
src/inmanta/data/__init__.py:86: note:      Subclass:
src/inmanta/data/__init__.py:86: note:          def _generate_next_value_(name, start: int, count: int, last_values: List[object]) -> object
src/inmanta/data/__init__.py:259: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/data/__init__.py:261: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/data/__init__.py:436: error: Dict entry 1 has incompatible type "str": "object"; expected "str": "Union[Type[datetime], Type[int], Type[str]]"  [dict-item]
src/inmanta/data/__init__.py:438: error: Dict entry 3 has incompatible type "str": "object"; expected "str": "Union[Type[datetime], Type[int], Type[str]]"  [dict-item]
src/inmanta/data/__init__.py:485: error: Dict entry 2 has incompatible type "str": "object"; expected "str": "Union[Type[datetime], Type[int], Type[str]]"  [dict-item]
src/inmanta/data/__init__.py:812: error: Incompatible return value type (got "object", expected "T")  [return-value]
src/inmanta/data/__init__.py:849: error: "_validate_single" of "Field" does not return a value  [func-returns-value]
src/inmanta/data/__init__.py:918: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/data/__init__.py:920: error: Incompatible types in assignment (expression has type "DocumentMeta", variable has type "Type[BaseDocument]")  [assignment]
src/inmanta/data/__init__.py:948: error: Missing type parameters for generic type "Field"  [type-arg]
src/inmanta/data/__init__.py:980: error: Missing type parameters for generic type "Field"  [type-arg]
src/inmanta/data/__init__.py:991: error: Missing type parameters for generic type "Field"  [type-arg]
src/inmanta/data/__init__.py:1013: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/data/__init__.py:1024: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/data/__init__.py:1028: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/data/__init__.py:1046: error: "Type[object]" has no attribute "__supertype__"  [attr-defined]
src/inmanta/data/__init__.py:1224: error: "BaseDocument" has no attribute "__name__"  [attr-defined]
src/inmanta/data/__init__.py:1300: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "List[Any]")  [assignment]
src/inmanta/data/__init__.py:1304: error: Argument "columns" to "copy_records_to_table" of "Connection" has incompatible type "KeysView[str]"; expected "Optional[List[str]]"  [arg-type]
src/inmanta/data/__init__.py:1308: error: "BaseDocument" has no attribute "_fields"; maybe "load_fields"?  [attr-defined]
src/inmanta/data/__init__.py:1474: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:1474: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "Optional[str]"  [arg-type]
src/inmanta/data/__init__.py:1490: error: Incompatible return value type (got "Sequence[Record]", expected "List[TBaseDocument]")  [return-value]
src/inmanta/data/__init__.py:1528: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:1528: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "Optional[str]"  [arg-type]
src/inmanta/data/__init__.py:1546: error: Incompatible return value type (got "Sequence[Record]", expected "List[TBaseDocument]")  [return-value]
src/inmanta/data/__init__.py:1554: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:1554: error: Argument 1 to "_get_composed_filter" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "Optional[str]"  [arg-type]
src/inmanta/data/__init__.py:1555: error: Incompatible types in assignment (expression has type "str", variable has type "Dict[str, object]")  [assignment]
src/inmanta/data/__init__.py:1557: error: Unsupported left operand type for + ("Dict[str, object]")  [operator]
src/inmanta/data/__init__.py:1558: error: Argument 1 to "_execute_query" of "BaseDocument" has incompatible type "Dict[str, object]"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:1639: error: Argument 2 to "get_range_filter" of "BaseDocument" has incompatible type "object"; expected "Union[List[Tuple[RangeOperator, datetime]], List[Tuple[RangeOperator, int]]]"  [arg-type]
src/inmanta/data/__init__.py:1717: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
src/inmanta/data/__init__.py:1933: error: Overloaded function implementation does not accept all possible arguments of signature 1  [misc]
src/inmanta/data/__init__.py:1960: error: "BaseDocument" has no attribute "__name__"  [attr-defined]
src/inmanta/data/__init__.py:2149: error: Argument "default" to "EnvironmentSetting" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"  [arg-type]
src/inmanta/data/__init__.py:2150: error: Argument "doc" to "EnvironmentSetting" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2210: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2217: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2242: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2250: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2259: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2268: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2277: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2284: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2291: error: Argument "validator" to "Setting" has incompatible type "Callable[[Dict[str, str]], Dict[str, str]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2300: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2308: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2315: error: Argument "validator" to "Setting" has incompatible type "Callable[[str], str]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2327: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2334: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2341: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2349: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[bool, str]], bool]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2356: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], Union[int, float]]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2363: error: Argument "validator" to "Setting" has incompatible type "Callable[[Union[float, int, str]], float]"; expected "Optional[Callable[[Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]], Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]]]"  [arg-type]
src/inmanta/data/__init__.py:2399: error: Argument 2 to "set" of "Environment" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"  [arg-type]
src/inmanta/data/__init__.py:2400: error: Incompatible return value type (got "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]], None]", expected "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]")  [return-value]
src/inmanta/data/__init__.py:2413: error: "None" not callable  [misc]
src/inmanta/data/__init__.py:2446: error: Argument 2 to "set" of "Environment" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"  [arg-type]
src/inmanta/data/__init__.py:2485: error: Value of type "Optional[Record]" is not indexable  [index]
src/inmanta/data/__init__.py:2503: error: Signature of "get_list" incompatible with supertype "BaseDocument"  [override]
src/inmanta/data/__init__.py:2503: note:      Superclass:
src/inmanta/data/__init__.py:2503: note:          @classmethod
src/inmanta/data/__init__.py:2503: note:          def get_list(cls, *, order_by_column: Optional[str] = ..., order: Optional[str] = ..., limit: Optional[int] = ..., offset: Optional[int] = ..., no_obj: Optional[bool] = ..., connection: Optional[Connection] = ..., **query: object) -> Coroutine[Any, Any, List[Environment]]
src/inmanta/data/__init__.py:2503: note:      Subclass:
src/inmanta/data/__init__.py:2503: note:          @classmethod
src/inmanta/data/__init__.py:2503: note:          def get_list(cls, *, order_by_column: Optional[str] = ..., order: Optional[str] = ..., limit: Optional[int] = ..., offset: Optional[int] = ..., no_obj: Optional[bool] = ..., connection: Optional[Connection] = ..., details: bool = ..., **query: object) -> Coroutine[Any, Any, List[Environment]]
src/inmanta/data/__init__.py:2520: error: Returning Any from function declared to return "List[TBaseDocument]"  [no-any-return]
src/inmanta/data/__init__.py:2520: error: Argument 2 for "super" not an instance of argument 1  [misc]
src/inmanta/data/__init__.py:2529: error: Returning Any from function declared to return "List[TBaseDocument]"  [no-any-return]
src/inmanta/data/__init__.py:2529: error: "Type[TBaseDocument]" has no attribute "get_list_without_details"  [attr-defined]
src/inmanta/data/__init__.py:2556: error: Returning Any from function declared to return "List[TBaseDocument]"  [no-any-return]
src/inmanta/data/__init__.py:2556: error: Argument 2 for "super" not an instance of argument 1  [misc]
src/inmanta/data/__init__.py:2608: error: Incompatible types in assignment (expression has type "str", variable has type "ResourceIdStr")  [assignment]
src/inmanta/data/__init__.py:2617: error: Incompatible return value type (got "Sequence[Parameter]", expected "List[Parameter]")  [return-value]
src/inmanta/data/__init__.py:2629: error: Incompatible return value type (got "Sequence[Parameter]", expected "List[Parameter]")  [return-value]
src/inmanta/data/__init__.py:2679: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2679: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2679: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2708: error: Incompatible types in assignment (expression has type "Union[UUID, bool, None]", variable has type "bool")  [assignment]
src/inmanta/data/__init__.py:2715: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:2718: error: Argument "id" to "Parameter" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:2719: error: Argument "name" to "Parameter" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2720: error: Argument "value" to "Parameter" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2721: error: Argument "source" to "Parameter" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2722: error: Argument "updated" to "Parameter" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:2723: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:2724: error: Argument "environment" to "Parameter" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:2765: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2765: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2765: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:2794: error: Incompatible types in assignment (expression has type "Union[str, Literal[False], None]", variable has type "bool")  [assignment]
src/inmanta/data/__init__.py:2799: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:2802: error: Argument "id" to "Fact" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:2803: error: Argument "name" to "Fact" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2804: error: Argument "value" to "Fact" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2805: error: Argument "source" to "Fact" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:2806: error: Argument "updated" to "Fact" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:2807: error: Argument "resource_id" to "Fact" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:2808: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:2809: error: Argument "environment" to "Fact" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:2834: error: Incompatible types in assignment (expression has type "str", variable has type "ResourceIdStr")  [assignment]
src/inmanta/data/__init__.py:3151: error: Incompatible return value type (got "Optional[Agent]", expected "Agent")  [return-value]
src/inmanta/data/__init__.py:3182: error: List comprehension has incompatible type List[object]; expected List[str]  [misc]
src/inmanta/data/__init__.py:3200: error: List comprehension has incompatible type List[object]; expected List[str]  [misc]
src/inmanta/data/__init__.py:3302: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3302: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3302: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3331: error: Incompatible types in assignment (expression has type "Union[str, bool, None]", variable has type "bool")  [assignment]
src/inmanta/data/__init__.py:3338: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:3342: error: Argument "name" to "Agent" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:3343: error: Argument "environment" to "Agent" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3344: error: Argument "last_failover" to "Agent" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3345: error: Argument "paused" to "Agent" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:3346: error: Argument "unpause_on_resume" to "Agent" has incompatible type "object"; expected "Optional[bool]"  [arg-type]
src/inmanta/data/__init__.py:3347: error: Argument "process_id" to "Agent" has incompatible type "object"; expected "Optional[UUID]"  [arg-type]
src/inmanta/data/__init__.py:3348: error: Argument "process_name" to "Agent" has incompatible type "object"; expected "Optional[str]"  [arg-type]
src/inmanta/data/__init__.py:3349: error: Argument "status" to "Agent" has incompatible type "object"; expected "AgentStatus"  [arg-type]
src/inmanta/data/__init__.py:3461: error: Missing type parameters for generic type "Dict"  [type-arg]
src/inmanta/data/__init__.py:3570: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3570: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3570: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:3602: error: Incompatible types in assignment (expression has type "Union[datetime, Literal[False], None]", variable has type "bool")  [assignment]
src/inmanta/data/__init__.py:3607: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:3611: error: Argument "id" to "CompileReport" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3612: error: Argument "remote_id" to "CompileReport" has incompatible type "object"; expected "Optional[UUID]"  [arg-type]
src/inmanta/data/__init__.py:3613: error: Argument "environment" to "CompileReport" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3614: error: Argument "requested" to "CompileReport" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3615: error: Argument "started" to "CompileReport" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3616: error: Argument "completed" to "CompileReport" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3617: error: Argument "success" to "CompileReport" has incompatible type "object"; expected "Optional[bool]"  [arg-type]
src/inmanta/data/__init__.py:3618: error: Argument "version" to "CompileReport" has incompatible type "object"; expected "Optional[int]"  [arg-type]
src/inmanta/data/__init__.py:3619: error: Argument "do_export" to "CompileReport" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:3620: error: Argument "force_update" to "CompileReport" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:3621: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3622: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3712: error: Argument "id" to "CompileRunReport" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3713: error: Argument "started" to "CompileRunReport" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:3714: error: Argument "completed" to "CompileRunReport" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3715: error: Argument "command" to "CompileRunReport" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:3716: error: Argument "name" to "CompileRunReport" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:3717: error: Argument "errstream" to "CompileRunReport" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:3718: error: Argument "outstream" to "CompileRunReport" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:3719: error: Argument "returncode" to "CompileRunReport" has incompatible type "object"; expected "Optional[int]"  [arg-type]
src/inmanta/data/__init__.py:3726: error: Argument "id" to "CompileDetails" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3727: error: Argument "remote_id" to "CompileDetails" has incompatible type "object"; expected "Optional[UUID]"  [arg-type]
src/inmanta/data/__init__.py:3728: error: Argument "environment" to "CompileDetails" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3729: error: Argument "requested" to "CompileDetails" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3730: error: Argument "started" to "CompileDetails" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3731: error: Argument "completed" to "CompileDetails" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:3732: error: Argument "success" to "CompileDetails" has incompatible type "object"; expected "Optional[bool]"  [arg-type]
src/inmanta/data/__init__.py:3733: error: Argument "version" to "CompileDetails" has incompatible type "object"; expected "Optional[int]"  [arg-type]
src/inmanta/data/__init__.py:3734: error: Argument "do_export" to "CompileDetails" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:3735: error: Argument "force_update" to "CompileDetails" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:3736: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3737: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3740: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3754: error: Argument "environment_variables" to "CompileRun" has incompatible type "Optional[Dict[str, Any]]"; expected "Dict[str, str]"  [arg-type]
src/inmanta/data/__init__.py:3776: error: Incompatible return value type (got "object", expected "str")  [return-value]
src/inmanta/data/__init__.py:3779: error: Missing type parameters for generic type "List"  [type-arg]
src/inmanta/data/__init__.py:3780: error: Incompatible return value type (got "object", expected "List[Any]")  [return-value]
src/inmanta/data/__init__.py:3784: error: Incompatible types in assignment (expression has type "object", variable has type "str")  [assignment]
src/inmanta/data/__init__.py:3846: error: Need type annotation for "_updates" (hint: "_updates: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/data/__init__.py:3856: error: Argument 1 to "loads" has incompatible type "Dict[str, Any]"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3866: error: Signature of "get_by_id" incompatible with supertype "BaseDocument"  [override]
src/inmanta/data/__init__.py:3866: note:      Superclass:
src/inmanta/data/__init__.py:3866: note:          @classmethod
src/inmanta/data/__init__.py:3866: note:          def get_by_id(cls, doc_id: UUID, connection: Optional[Connection] = ...) -> Coroutine[Any, Any, Optional[ResourceAction]]
src/inmanta/data/__init__.py:3866: note:      Subclass:
src/inmanta/data/__init__.py:3866: note:          @classmethod
src/inmanta/data/__init__.py:3866: note:          def get_by_id(cls, doc_id: UUID) -> Coroutine[Any, Any, ResourceAction]
src/inmanta/data/__init__.py:3867: error: Incompatible return value type (got "Optional[ResourceAction]", expected "ResourceAction")  [return-value]
src/inmanta/data/__init__.py:3986: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:3989: error: Argument "action_id" to "ResourceLog" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:3990: error: Argument "action" to "ResourceLog" has incompatible type "object"; expected "ResourceAction"  [arg-type]
src/inmanta/data/__init__.py:3991: error: Argument "timestamp" to "ResourceLog" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:4032: error: Incompatible return value type (got "Optional[ResourceAction]", expected "ResourceAction")  [return-value]
src/inmanta/data/__init__.py:4083: error: Argument 1 to "add_logs" of "ResourceAction" has incompatible type "List[Dict[str, Any]]"; expected "Optional[str]"  [arg-type]
src/inmanta/data/__init__.py:4086: error: Argument 1 to "add_changes" of "ResourceAction" has incompatible type "Dict[str, Any]"; expected "Dict[ResourceIdStr, Dict[str, object]]"  [arg-type]
src/inmanta/data/__init__.py:4116: error: Argument "days" to "timedelta" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"; expected "float"  [arg-type]
src/inmanta/data/__init__.py:4217: error: Argument "changes" to "ResourceAction" has incompatible type "Optional[Dict[ResourceIdStr, Dict[str, object]]]"; expected "Optional[Dict[str, Any]]"  [arg-type]
src/inmanta/data/__init__.py:4294: error: Key expression in dictionary comprehension has incompatible type "object"; expected type "ResourceVersionIdStr"  [misc]
src/inmanta/data/__init__.py:4325: error: Incompatible return value type (got "Sequence[Resource]", expected "List[Resource]")  [return-value]
src/inmanta/data/__init__.py:4339: error: Incompatible return value type (got "Sequence[Resource]", expected "List[Resource]")  [return-value]
src/inmanta/data/__init__.py:4377: error: Argument 2 to "is_sub_dict" has incompatible type "Dict[str, Any]"; expected "Dict[Union[UUID, StrictNonIntBool, int, float, datetime, str], Union[UUID, StrictNonIntBool, int, float, datetime, str]]"  [arg-type]
src/inmanta/data/__init__.py:4422: error: Argument 1 to "parse_id" of "Id" has incompatible type "object"; expected "Union[ResourceVersionIdStr, ResourceIdStr]"  [arg-type]
src/inmanta/data/__init__.py:4456: error: Incompatible types in assignment (expression has type "Dict[str, object]", variable has type "Record")  [assignment]
src/inmanta/data/__init__.py:4457: error: Unsupported target for indexed assignment ("Record")  [index]
src/inmanta/data/__init__.py:4457: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4458: error: Unsupported target for indexed assignment ("Record")  [index]
src/inmanta/data/__init__.py:4459: error: Argument 1 to "parse_id" of "Id" has incompatible type "object"; expected "Union[ResourceVersionIdStr, ResourceIdStr]"  [arg-type]
src/inmanta/data/__init__.py:4460: error: Unsupported target for indexed assignment ("Record")  [index]
src/inmanta/data/__init__.py:4463: error: Argument 1 to "append" of "list" has incompatible type "Resource"; expected "Record"  [arg-type]
src/inmanta/data/__init__.py:4464: error: Incompatible return value type (got "List[Record]", expected "List[Resource]")  [return-value]
src/inmanta/data/__init__.py:4471: error: Incompatible types in assignment (expression has type "str", variable has type "Optional[List[str]]")  [assignment]
src/inmanta/data/__init__.py:4473: error: Incompatible types in assignment (expression has type "str", variable has type "Optional[List[str]]")  [assignment]
src/inmanta/data/__init__.py:4475: error: Unsupported operand types for + ("str" and "List[str]")  [operator]
src/inmanta/data/__init__.py:4475: error: Unsupported operand types for + ("str" and "None")  [operator]
src/inmanta/data/__init__.py:4475: note: Right operand is of type "Optional[List[str]]"
src/inmanta/data/__init__.py:4480: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4609: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:4613: error: Argument "resource_id" to "LatestReleasedResource" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:4614: error: Argument "resource_version_id" to "LatestReleasedResource" has incompatible type "object"; expected "ResourceVersionIdStr"  [arg-type]
src/inmanta/data/__init__.py:4615: error: Argument 1 to "get_details_from_resource_id" of "Resource" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:4617: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4846: error: Argument 1 to "parse_id" of "Id" has incompatible type "object"; expected "Union[ResourceVersionIdStr, ResourceIdStr]"  [arg-type]
src/inmanta/data/__init__.py:4848: error: Argument "resource_id" to "ReleasedResourceDetails" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:4849: error: Argument "resource_type" to "ReleasedResourceDetails" has incompatible type "object"; expected "ResourceType"  [arg-type]
src/inmanta/data/__init__.py:4850: error: Argument "agent" to "ReleasedResourceDetails" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:4852: error: Argument "id_attribute_value" to "ReleasedResourceDetails" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:4853: error: Argument "last_deploy" to "ReleasedResourceDetails" has incompatible type "object"; expected "Optional[datetime]"  [arg-type]
src/inmanta/data/__init__.py:4854: error: Argument "first_generated_time" to "ReleasedResourceDetails" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:4855: error: Argument "first_generated_version" to "ReleasedResourceDetails" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:4856: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4858: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4980: error: Argument "attribute_hash" to "ResourceHistory" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:4981: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:4982: error: Argument "date" to "ResourceHistory" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:4985: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:5035: error: Argument 1 to "create_from_db_result" of "ResourceDeploySummary" has incompatible type "Dict[object, object]"; expected "Dict[str, int]"  [arg-type]
src/inmanta/data/__init__.py:5074: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5074: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5074: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5111: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:5115: error: Argument "resource_id" to "VersionedResource" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:5116: error: Argument "resource_version_id" to "VersionedResource" has incompatible type "object"; expected "ResourceVersionIdStr"  [arg-type]
src/inmanta/data/__init__.py:5117: error: Argument 1 to "get_details_from_resource_id" of "Resource" has incompatible type "object"; expected "ResourceIdStr"  [arg-type]
src/inmanta/data/__init__.py:5118: error: Argument 1 to "loads" has incompatible type "object"; expected "Union[str, bytes]"  [arg-type]
src/inmanta/data/__init__.py:5129: error: Argument 1 of "insert_many" is incompatible with supertype "BaseDocument"; supertype defines the argument type as "Sequence[BaseDocument]"  [override]
src/inmanta/data/__init__.py:5129: note: This violates the Liskov substitution principle
src/inmanta/data/__init__.py:5129: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
src/inmanta/data/__init__.py:5203: error: Argument 1 to "__init__" of "BaseDocument" has incompatible type "**Dict[str, object]"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:5204: error: Need type annotation for "_status" (hint: "_status: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/data/__init__.py:5227: error: Invalid index type "str" for "str"; expected type "Union[SupportsIndex, slice]"  [index]
src/inmanta/data/__init__.py:5283: error: Incompatible types in assignment (expression has type "Dict[str, object]", variable has type "Record")  [assignment]
src/inmanta/data/__init__.py:5285: error: Unsupported target for indexed assignment ("Record")  [index]
src/inmanta/data/__init__.py:5285: error: Argument 1 to "_get_status_field" of "ConfigurationModel" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:5285: error: Argument 2 to "_get_status_field" of "ConfigurationModel" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5288: error: "Record" has no attribute "pop"  [attr-defined]
src/inmanta/data/__init__.py:5289: error: Argument 1 to "_get_status_field" of "ConfigurationModel" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:5289: error: "Record" has no attribute "pop"  [attr-defined]
src/inmanta/data/__init__.py:5293: error: Argument 1 to "append" of "list" has incompatible type "ConfigurationModel"; expected "Record"  [arg-type]
src/inmanta/data/__init__.py:5294: error: Incompatible return value type (got "List[Record]", expected "List[ConfigurationModel]")  [return-value]
src/inmanta/data/__init__.py:5351: error: Returning Any from function declared to return "Optional[int]"  [no-any-return]
src/inmanta/data/__init__.py:5351: error: No overload variant of "int" matches argument type "object"  [call-overload]
src/inmanta/data/__init__.py:5351: note: Possible overload variants:
src/inmanta/data/__init__.py:5351: note:     def __new__(cls, Union[str, bytes, array[Any], mmap, _CData, PickleBuffer, SupportsInt, SupportsIndex, SupportsTrunc] = ...) -> int
src/inmanta/data/__init__.py:5351: note:     def __new__(cls, Union[str, bytes], base: SupportsIndex) -> int
src/inmanta/data/__init__.py:5367: error: Incompatible return value type (got "List[object]", expected "List[str]")  [return-value]
src/inmanta/data/__init__.py:5443: error: Invalid index type "object" for "Type[VersionState]"; expected type "str"  [index]
src/inmanta/data/__init__.py:5522: error: Incompatible types in assignment (expression has type "object", variable has type "int")  [assignment]
src/inmanta/data/__init__.py:5589: error: Argument 1 to "list" has incompatible type "Set[str]"; expected "Iterable[Dict[str, Any]]"  [arg-type]
src/inmanta/data/__init__.py:5601: error: Invalid index type "Dict[str, Any]" for "Dict[str, List[str]]"; expected type "str"  [index]
src/inmanta/data/__init__.py:5602: error: Argument 1 to "extend" of "list" has incompatible type "List[str]"; expected "Iterable[Dict[str, Any]]"  [arg-type]
src/inmanta/data/__init__.py:5606: error: Incompatible return value type (got "Tuple[Set[str], Set[Any]]", expected "Tuple[Set[ResourceVersionIdStr], Set[ResourceVersionIdStr]]")  [return-value]
src/inmanta/data/__init__.py:5665: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5665: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5665: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5702: error: Argument "version" to "DesiredStateVersion" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5703: error: Argument "date" to "DesiredStateVersion" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:5704: error: Argument "total" to "DesiredStateVersion" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5705: error: Argument "name" to "DesiredStateLabel" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5705: error: Argument "message" to "DesiredStateLabel" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5708: error: Argument "status" to "DesiredStateVersion" has incompatible type "object"; expected "DesiredStateVersionStatus"  [arg-type]
src/inmanta/data/__init__.py:5939: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5939: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5939: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/__init__.py:5968: error: Incompatible types in assignment (expression has type "Union[UUID, bool, None]", variable has type "bool")  [assignment]
src/inmanta/data/__init__.py:5975: error: Incompatible types in assignment (expression has type "Iterable[Record]", variable has type "Sequence[Record]")  [assignment]
src/inmanta/data/__init__.py:5978: error: Argument "id" to "Notification" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:5979: error: Argument "title" to "Notification" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5980: error: Argument "message" to "Notification" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5981: error: Argument "severity" to "Notification" has incompatible type "object"; expected "NotificationSeverity"  [arg-type]
src/inmanta/data/__init__.py:5982: error: Argument "created" to "Notification" has incompatible type "object"; expected "datetime"  [arg-type]
src/inmanta/data/__init__.py:5983: error: Argument "read" to "Notification" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:5984: error: Argument "cleared" to "Notification" has incompatible type "object"; expected "bool"  [arg-type]
src/inmanta/data/__init__.py:5985: error: Argument "uri" to "Notification" has incompatible type "object"; expected "str"  [arg-type]
src/inmanta/data/__init__.py:5986: error: Argument "environment" to "Notification" has incompatible type "object"; expected "UUID"  [arg-type]
src/inmanta/data/__init__.py:5997: error: Argument "days" to "timedelta" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"; expected "float"  [arg-type]
src/inmanta/data/__init__.py:6040: error: "DocumentMeta" has no attribute "set_connection_pool"  [attr-defined]
src/inmanta/data/__init__.py:6047: error: "DocumentMeta" has no attribute "close_connection_pool"  [attr-defined]
src/inmanta/data/__init__.py:6071: error: Incompatible types in "await" (actual type "Pool", expected type "Awaitable[Any]")  [misc]
src/inmanta/data/__init__.py:6088: error: Returning Any from function declared to return "Pool"  [no-any-return]
src/inmanta/agent/io/remote.py:24: error: Skipping analyzing "execnet": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/agent/io/remote.py:24: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/inmanta/agent/io/remote.py:97: error: Argument "hostname" to "HostNotFoundException" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/agent/io/remote.py:107: error: Argument "hostname" to "HostNotFoundException" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/agent/io/remote.py:107: error: Argument "error" to "HostNotFoundException" has incompatible type "BrokenPipeError"; expected "str"  [arg-type]
src/inmanta/agent/io/remote.py:133: error: Item "None" of "Optional[Any]" has no attribute "remote_exec"  [union-attr]
src/inmanta/agent/io/remote.py:158: error: Incompatible return value type (got "object", expected "bytes")  [return-value]
src/inmanta/agent/io/remote.py:160: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/util.py:62: error: Argument "key" to "sorted" has incompatible type "Callable[[T], S]"; expected "Callable[[T], Union[SupportsDunderLT, SupportsDunderGT]]"  [arg-type]
src/inmanta/util.py:117: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/util.py:297: error: Return value expected  [return-value]
src/inmanta/util.py:461: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/util.py:461: error: Missing type parameters for generic type "Coroutine"  [type-arg]
src/inmanta/util.py:461: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/util.py:466: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/util.py:486: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/util.py:486: error: Incompatible types in "await" (actual type "Union[bool, Awaitable[bool]]", expected type "Awaitable[Any]")  [misc]
src/inmanta/util.py:488: error: Incompatible return value type (got "Union[bool, Awaitable[bool]]", expected "bool")  [return-value]
src/inmanta/util.py:509: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/util.py:510: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/util.py:519: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/util.py:519: error: Missing type parameters for generic type "Coroutine"  [type-arg]
src/inmanta/util.py:519: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/util.py:531: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/resources.py:179: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/resources.py:312: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/resources.py:316: error: Incompatible return value type (got "Unknown", expected "str")  [return-value]
src/inmanta/resources.py:641: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/protocol/common.py:208: error: Dict entry 0 has incompatible type "str": "Dict[str, List[str]]"; expected "str": "Union[BaseModel, UUID, StrictNonIntBool, float, datetime, str]"  [dict-item]
src/inmanta/protocol/common.py:258: error: Missing type parameters for generic type "ReturnValue"  [type-arg]
src/inmanta/protocol/common.py:265: error: Argument 2 to "get_body" of "ReturnValue" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/protocol/common.py:341: error: Missing type parameters for generic type "classmethod"  [type-arg]
src/inmanta/protocol/common.py:434: error: Argument "text" to "parse" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/protocol/common.py:478: error: Returning Any from function declared to return "Type[BaseModel]"  [no-any-return]
src/inmanta/protocol/common.py:478: error: No overload variant of "create_model" matches argument types "str", "Dict[str, Tuple[object, Optional[object]]]", "Type[MethodArgumentsBaseModel]"  [call-overload]
src/inmanta/protocol/common.py:478: note: Possible overload variants:
src/inmanta/protocol/common.py:478: note:     def create_model(__model_name, str, *, __config__: Optional[Type[BaseConfig]] = ..., __base__: None = ..., __module__: str = ..., __validators__: Dict[str, classmethod[Any]] = ..., __cls_kwargs__: Dict[str, Any] = ..., **field_definitions: Any) -> Type[BaseModel]
src/inmanta/protocol/common.py:478: note:     def [Model <: BaseModel] create_model(__model_name, str, *, __config__: Optional[Type[BaseConfig]] = ..., __base__: Union[Type[Model], Tuple[Type[Model], ...]], __module__: str = ..., __validators__: Dict[str, classmethod[Any]] = ..., __cls_kwargs__: Dict[str, Any] = ..., **field_definitions: Any) -> Type[Model]
src/inmanta/protocol/common.py:542: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/protocol/common.py:547: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/protocol/common.py:549: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/common.py:557: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/common.py:571: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/protocol/common.py:599: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/common.py:614: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/common.py:621: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/common.py:630: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/common.py:645: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/common.py:763: error: Returning Any from function declared to return "int"  [no-any-return]
src/inmanta/protocol/common.py:784: error: Argument 1 to "_get_http_status_code_for_exception" of "MethodProperties" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/protocol/common.py:785: error: Incompatible types in assignment (expression has type "Optional[str]", target has type "str")  [assignment]
src/inmanta/protocol/common.py:847: error: Need type annotation for "params_to_add" (hint: "params_to_add: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/protocol/common.py:873: error: Incompatible return value type (got "Dict[str, Union[Any, List[Any]]]", expected "Dict[str, str]")  [return-value]
src/inmanta/protocol/common.py:935: error: Returning Any from function declared to return "Union[Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None], JSONSerializable]"  [no-any-return]
src/inmanta/protocol/common.py:994: error: Argument 2 has incompatible type "bytes"; expected "str"  [arg-type]
src/inmanta/protocol/common.py:1000: error: Call to untyped function (unknown) in typed context  [no-untyped-call]
src/inmanta/protocol/common.py:1025: error: Incompatible types in assignment (expression has type "str", variable has type "bytes")  [assignment]
src/inmanta/protocol/common.py:1030: error: Argument 2 has incompatible type "bytes"; expected "str"  [arg-type]
src/inmanta/protocol/common.py:1065: error: "Callable[[Result], Optional[Dict[str, Any]]]" has no attribute "setter"  [attr-defined]
src/inmanta/protocol/common.py:1065: error: Untyped decorator makes function "set_result" untyped  [misc]
src/inmanta/ast/statements/__init__.py:49: error: Cannot find implementation or library stub for module named "inmanta.ast.assign"  [import]
src/inmanta/ast/statements/__init__.py:64: error: Incompatible types in assignment (expression has type "None", variable has type "Namespace")  [assignment]
src/inmanta/ast/statements/__init__.py:75: error: Returning Any from function declared to return "Location"  [no-any-return]
src/inmanta/ast/statements/__init__.py:145: error: Need type annotation for "target"  [var-annotated]
src/inmanta/ast/statements/__init__.py:149: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:160: error: Missing type parameters for generic type "ResultCollector"  [type-arg]
src/inmanta/ast/statements/__init__.py:161: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:169: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:197: error: Incompatible types in assignment (expression has type "object", variable has type "Sequence[EagerPromise]")  [assignment]
src/inmanta/ast/statements/__init__.py:227: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/__init__.py:238: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:288: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:296: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:360: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:427: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:446: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:475: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:476: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/__init__.py:568: error: Incompatible types in assignment (expression has type "None", variable has type "NamedType")  [assignment]
src/inmanta/ast/statements/__init__.py:583: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/statements/__init__.py:583: note: Use "-> None" if function does not return a value
src/inmanta/ast/attribute.py:82: error: Incompatible types in assignment (expression has type "property", variable has type "Type")  [assignment]
src/inmanta/ast/attribute.py:119: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/attribute.py:175: error: Need type annotation for "source_annotations" (hint: "source_annotations: List[<type>] = ...")  [var-annotated]
src/inmanta/ast/attribute.py:176: error: Need type annotation for "target_annotations" (hint: "target_annotations: List[<type>] = ...")  [var-annotated]
src/inmanta/ast/attribute.py:192: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/attribute.py:193: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/protocol/rest/__init__.py:154: error: Returning Any from function declared to return "Optional[object]"  [no-any-return]
src/inmanta/protocol/rest/__init__.py:166: error: Argument 2 has incompatible type "Dict[str, object]"; expected "Dict[str, str]"  [arg-type]
src/inmanta/protocol/rest/__init__.py:254: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:256: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:258: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:266: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:267: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:277: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:280: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:303: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:309: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:318: error: Module has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:324: error: Module has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/rest/__init__.py:473: error: Argument 1 to "UUID" has incompatible type "object"; expected "Optional[str]"  [arg-type]
src/inmanta/protocol/rest/__init__.py:479: error: Argument 2 to "authorize_request" has incompatible type "Dict[str, object]"; expected "Dict[str, str]"  [arg-type]
src/inmanta/protocol/rest/__init__.py:484: error: "Callable[..., Coroutine[Any, Any, Union[int, Tuple[int, Optional[Dict[str, Any]]], ReturnValue[Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]], ReturnValue[None], Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]]]]" has no attribute "__protocol_mapping__"  [attr-defined]
src/inmanta/protocol/methods_v2.py:78: error: Incompatible default for argument "project_id" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods_v2.py:124: error: Incompatible default for argument "environment_id" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods_v2.py:150: error: Incompatible default for argument "repository" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods_v2.py:151: error: Incompatible default for argument "branch" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods_v2.py:201: error: Module has no attribute "ArgOption"  [attr-defined]
src/inmanta/protocol/methods_v2.py:253: error: Module has no attribute "ArgOption"  [attr-defined]
src/inmanta/protocol/methods_v2.py:273: error: Module has no attribute "ArgOption"  [attr-defined]
src/inmanta/protocol/methods_v2.py:548: error: Cannot determine type of "RVID_OPTS"  [has-type]
src/inmanta/protocol/methods_v2.py:580: error: Cannot determine type of "RVID_OPTS"  [has-type]
src/inmanta/protocol/methods_v2.py:604: error: Cannot determine type of "RVID_OPTS"  [has-type]
src/inmanta/protocol/methods_v2.py:628: error: Cannot determine type of "RVID_OPTS"  [has-type]
src/inmanta/protocol/methods_v2.py:934: error: Variable "inmanta.data.model.PromoteTriggerMethod" is not valid as a type  [valid-type]
src/inmanta/protocol/methods_v2.py:934: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src/inmanta/protocol/methods.py:34: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:36: error: Incompatible types in assignment (expression has type "Optional[Environment]", variable has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:39: error: Incompatible return value type (got "UUID", expected "Environment")  [return-value]
src/inmanta/protocol/methods.py:42: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:47: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:55: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:71: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:71: error: Incompatible default for argument "project_id" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:81: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:88: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:95: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:95: note: Use "-> None" if function does not return a value
src/inmanta/protocol/methods.py:102: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:110: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:111: error: Incompatible default for argument "repository" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:111: error: Incompatible default for argument "branch" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:111: error: Incompatible default for argument "environment_id" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:125: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:125: error: Incompatible default for argument "repository" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:125: error: Incompatible default for argument "branch" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:137: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:149: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:149: note: Use "-> None" if function does not return a value
src/inmanta/protocol/methods.py:161: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:161: error: Incompatible default for argument "versions" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:161: error: Incompatible default for argument "resources" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:183: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:197: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:211: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:225: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:240: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:240: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:262: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:262: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:262: error: Incompatible default for argument "metadata" (default has type "None", argument has type "Dict[Any, Any]")  [assignment]
src/inmanta/protocol/methods.py:281: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:301: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:301: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:322: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:322: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:343: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:360: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:376: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:390: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:390: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:411: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:412: error: Incompatible default for argument "logs" (default has type "None", argument has type "bool")  [assignment]
src/inmanta/protocol/methods.py:412: error: Incompatible default for argument "status" (default has type "None", argument has type "bool")  [assignment]
src/inmanta/protocol/methods.py:412: error: Incompatible default for argument "log_action" (default has type "None", argument has type "ResourceAction")  [assignment]
src/inmanta/protocol/methods.py:430: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:431: error: Incompatible default for argument "sid" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:431: error: Incompatible default for argument "version" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:447: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:449: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:452: error: Incompatible default for argument "started" (default has type "None", argument has type "datetime")  [assignment]
src/inmanta/protocol/methods.py:453: error: Incompatible default for argument "finished" (default has type "None", argument has type "datetime")  [assignment]
src/inmanta/protocol/methods.py:454: error: Incompatible default for argument "status" (default has type "None", argument has type "ResourceState")  [assignment]
src/inmanta/protocol/methods.py:455: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:456: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:457: error: Incompatible default for argument "change" (default has type "None", argument has type "Change")  [assignment]
src/inmanta/protocol/methods.py:484: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:484: error: Incompatible default for argument "start" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:484: error: Incompatible default for argument "limit" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:495: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:495: error: Incompatible default for argument "include_logs" (default has type "None", argument has type "bool")  [assignment]
src/inmanta/protocol/methods.py:495: error: Incompatible default for argument "log_filter" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:495: error: Incompatible default for argument "limit" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:511: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:521: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:524: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:525: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:526: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:526: error: Incompatible default for argument "unknowns" (default has type "None", argument has type "List[Any]")  [assignment]
src/inmanta/protocol/methods.py:527: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:527: error: Incompatible default for argument "version_info" (default has type "None", argument has type "Dict[Any, Any]")  [assignment]
src/inmanta/protocol/methods.py:528: error: Incompatible default for argument "compiler_version" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:551: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:551: error: Incompatible default for argument "agent_trigger_method" (default has type "None", argument has type "AgentTriggerMethod")  [assignment]
src/inmanta/protocol/methods.py:564: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:567: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:567: error: Incompatible default for argument "agents" (default has type "None", argument has type "List[Any]")  [assignment]
src/inmanta/protocol/methods.py:582: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:592: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:592: error: Incompatible default for argument "version" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:602: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:612: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:612: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:627: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:647: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:659: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:659: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:670: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:687: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:687: error: Incompatible default for argument "resource_id" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:709: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:714: error: Incompatible default for argument "resource_id" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:715: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:738: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:738: error: Incompatible default for argument "resource_id" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:751: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:751: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:770: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:770: error: Missing type parameters for generic type "list"  [type-arg]
src/inmanta/protocol/methods.py:788: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:788: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:799: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:809: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:809: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/protocol/methods.py:823: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:833: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:833: error: Incompatible default for argument "start" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:833: error: Incompatible default for argument "end" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:833: error: Incompatible default for argument "limit" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:845: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:857: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:858: error: Incompatible default for argument "environment" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:858: error: Incompatible default for argument "start" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:858: error: Incompatible default for argument "end" (default has type "None", argument has type "UUID")  [assignment]
src/inmanta/protocol/methods.py:858: error: Incompatible default for argument "limit" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:877: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:888: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:899: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:899: error: Incompatible default for argument "start" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:899: error: Incompatible default for argument "end" (default has type "None", argument has type "str")  [assignment]
src/inmanta/protocol/methods.py:899: error: Incompatible default for argument "limit" (default has type "None", argument has type "int")  [assignment]
src/inmanta/protocol/methods.py:917: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:917: note: Use "-> None" if function does not return a value
src/inmanta/protocol/methods.py:929: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:936: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:950: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/methods.py:950: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/protocol/methods.py:970: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/endpoints.py:47: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/protocol/endpoints.py:54: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/protocol/endpoints.py:78: error: "Callable[..., Any]" has no attribute "__api_version__"  [attr-defined]
src/inmanta/protocol/endpoints.py:79: error: "Callable[..., Any]" has no attribute "__api_version__"  [attr-defined]
src/inmanta/protocol/endpoints.py:80: error: "Callable[..., Any]" has no attribute "__api_version__"  [attr-defined]
src/inmanta/protocol/endpoints.py:284: error: Unpacking a string is disallowed  [misc]
src/inmanta/protocol/endpoints.py:285: error: Cannot determine type of "value"  [has-type]
src/inmanta/protocol/endpoints.py:286: error: Cannot determine type of "key"  [has-type]
src/inmanta/protocol/endpoints.py:286: error: Cannot determine type of "value"  [has-type]
src/inmanta/protocol/endpoints.py:288: error: Cannot determine type of "key"  [has-type]
src/inmanta/protocol/endpoints.py:288: error: Cannot determine type of "value"  [has-type]
src/inmanta/protocol/endpoints.py:291: error: Argument 1 to "_execute_call" of "RESTBase" has incompatible type "Optional[Dict[str, str]]"; expected "Dict[str, str]"  [arg-type]
src/inmanta/protocol/endpoints.py:291: error: Argument 3 to "_execute_call" of "RESTBase" has incompatible type "Optional[UrlMethod]"; expected "UrlMethod"  [arg-type]
src/inmanta/protocol/endpoints.py:295: error: Unsupported right operand type for in ("Union[BaseModel, UUID, StrictNonIntBool, float, datetime, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]]]")  [operator]
src/inmanta/protocol/endpoints.py:296: error: Value of type "Union[BaseModel, UUID, StrictNonIntBool, float, datetime, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]]]" is not indexable  [index]
src/inmanta/protocol/endpoints.py:296: error: No overload variant of "__getitem__" of "Sequence" matches argument type "str"  [call-overload]
src/inmanta/protocol/endpoints.py:296: note: Possible overload variants:
src/inmanta/protocol/endpoints.py:296: note:     def __getitem__(self, int) -> Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]
src/inmanta/protocol/endpoints.py:296: note:     def __getitem__(self, slice) -> Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]]
src/inmanta/protocol/endpoints.py:296: error: Incompatible types in assignment (expression has type "Union[Any, BaseModel, UUID, StrictNonIntBool, float, datetime, str]", variable has type "str")  [assignment]
src/inmanta/protocol/endpoints.py:344: error: Incompatible types in assignment (expression has type "None", variable has type "RESTClient")  [assignment]
src/inmanta/protocol/endpoints.py:357: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/protocol/endpoints.py:386: error: Argument "args" to "_call" of "Client" has incompatible type "Tuple[object, ...]"; expected "List[object]"  [arg-type]
src/inmanta/protocol/endpoints.py:438: error: Returning Any from function declared to return "Result"  [no-any-return]
src/inmanta/parser/cache.py:103: error: Argument 1 to "ASTUnpickler" has incompatible type "BufferedReader"; expected "BytesIO"  [arg-type]
src/inmanta/loader.py:152: error: Argument 1 to "getsourcefile" has incompatible type "object"; expected "Union[Module, Type[Any], MethodType, FunctionType, TracebackType, FrameType, CodeType, Callable[..., Any]]"  [arg-type]
src/inmanta/loader.py:351: error: Return type "bytes" of "get_source" incompatible with return type "Optional[str]" in supertype "InspectLoader"  [override]
src/inmanta/loader.py:462: error: Incompatible types in assignment (expression has type "None", variable has type "PluginModuleFinder")  [assignment]
src/inmanta/loader.py:482: error: Argument 1 to "remove" of "list" has incompatible type "PluginModuleFinder"; expected "_MetaPathFinder"  [arg-type]
src/inmanta/loader.py:483: error: Incompatible types in assignment (expression has type "None", variable has type "PluginModuleFinder")  [assignment]
src/inmanta/execute/proxy.py:90: error: Returning Any from function declared to return "Instance"  [no-any-return]
src/inmanta/execute/proxy.py:144: error: Argument 1 to "SequenceProxy" has incompatible type "object"; expected "Sequence[Any]"  [arg-type]
src/inmanta/execute/proxy.py:147: error: Argument 1 to "CallProxy" has incompatible type "object"; expected "Callable[..., object]"  [arg-type]
src/inmanta/execute/proxy.py:149: error: Argument 1 to "DynamicProxy" has incompatible type "object"; expected "Instance"  [arg-type]
src/inmanta/execute/proxy.py:151: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:158: error: Argument 1 to "AttributeNotFound" has incompatible type "Optional[Locatable]"; expected "Optional[Statement]"  [arg-type]
src/inmanta/execute/proxy.py:185: error: "object" has no attribute "_get_instance"  [attr-defined]
src/inmanta/execute/proxy.py:191: error: "object" has no attribute "_get_instance"  [attr-defined]
src/inmanta/execute/proxy.py:193: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/execute/proxy.py:193: error: Unsupported left operand type for < ("Instance")  [operator]
src/inmanta/execute/proxy.py:200: error: Missing type parameters for generic type "Sequence"  [type-arg]
src/inmanta/execute/proxy.py:201: error: Argument 2 to "__init__" of "DynamicProxy" has incompatible type "Sequence[Any]"; expected "Instance"  [arg-type]
src/inmanta/execute/proxy.py:206: error: Argument 1 to "RuntimeException" has incompatible type "SequenceProxy"; expected "Optional[Locatable]"  [arg-type]
src/inmanta/execute/proxy.py:211: error: Argument 1 to "len" has incompatible type "Instance"; expected "Sized"  [arg-type]
src/inmanta/execute/proxy.py:213: error: Missing type parameters for generic type "Iterable"  [type-arg]
src/inmanta/execute/proxy.py:216: error: "Instance" has no attribute "__iter__"; maybe "__str__"? (not iterable)  [attr-defined]
src/inmanta/execute/proxy.py:220: error: "Iterable[Any]" has no attribute "__next__"  [attr-defined]
src/inmanta/execute/proxy.py:223: error: Missing type parameters for generic type "Mapping"  [type-arg]
src/inmanta/execute/proxy.py:225: error: Argument 2 to "__init__" of "DynamicProxy" has incompatible type "Dict[object, object]"; expected "Instance"  [arg-type]
src/inmanta/execute/proxy.py:227: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:230: error: Argument 1 to "RuntimeException" has incompatible type "DictProxy"; expected "Optional[Locatable]"  [arg-type]
src/inmanta/execute/proxy.py:232: error: Value of type "Instance" is not indexable  [index]
src/inmanta/execute/proxy.py:235: error: Argument 1 to "len" has incompatible type "Instance"; expected "Sized"  [arg-type]
src/inmanta/execute/proxy.py:237: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:240: error: "Instance" has no attribute "__iter__"; maybe "__str__"? (not iterable)  [attr-defined]
src/inmanta/execute/proxy.py:253: error: Argument 2 to "__init__" of "DynamicProxy" has incompatible type "Callable[..., object]"; expected "Instance"  [arg-type]
src/inmanta/execute/proxy.py:255: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:258: error: "Instance" not callable  [operator]
src/inmanta/execute/proxy.py:267: error: Argument 2 to "__init__" of "DynamicProxy" has incompatible type "Iterable[object]"; expected "Instance"  [arg-type]
src/inmanta/execute/proxy.py:269: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:272: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/execute/proxy.py:274: error: No overload variant of "next" matches argument type "Instance"  [call-overload]
src/inmanta/execute/proxy.py:274: note: Possible overload variants:
src/inmanta/execute/proxy.py:274: note:     def [_T] next(__i, SupportsNext[_T]) -> _T
src/inmanta/execute/proxy.py:274: note:     def [_T, _VT] next(__i, SupportsNext[_T], _VT) -> Union[_T, _VT]
src/inmanta/execute/dataflow/datatrace.py:84: error: Missing type parameters for generic type "Assignment"  [type-arg]
src/inmanta/execute/dataflow/datatrace.py:209: error: Missing type parameters for generic type "Assignment"  [type-arg]
src/inmanta/ast/statements/assign.py:90: error: Missing type parameters for generic type "ResultCollector"  [type-arg]
src/inmanta/ast/statements/assign.py:91: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/assign.py:95: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/assign.py:111: error: Argument 3 to "ExecutionUnit" has incompatible type "ListLiteral"; expected "ResultVariable[object]"  [arg-type]
src/inmanta/ast/statements/assign.py:240: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/assign.py:261: error: Argument 4 to "SetAttributeHelper" has incompatible type "Dict[object, VariableABC[Any]]"; expected "Dict[object, ResultVariable[Any]]"  [arg-type]
src/inmanta/ast/statements/assign.py:303: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/assign.py:304: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/assign.py:310: error: Argument 5 to "__init__" of "ExecutionUnit" has incompatible type "Dict[object, ResultVariable[Any]]"; expected "Dict[object, VariableABC[Any]]"  [arg-type]
src/inmanta/ast/statements/assign.py:310: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/ast/statements/assign.py:310: note: Consider using "Mapping" instead, which is covariant in the value type
src/inmanta/ast/statements/assign.py:440: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/assign.py:441: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/assign.py:443: error: Need type annotation for "temp"  [var-annotated]
src/inmanta/ast/statements/assign.py:450: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/assign.py:452: error: "Type" has no attribute "lookup_index"  [attr-defined]
src/inmanta/ast/statements/assign.py:503: error: Incompatible types in assignment (expression has type "None", variable has type "Type")  [assignment]
src/inmanta/ast/statements/assign.py:506: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/assign.py:526: error: "Type" has no attribute "lookup_index"  [attr-defined]
src/inmanta/ast/blocks.py:39: error: Incompatible types in assignment (expression has type "None", variable has type "ExecutionContext")  [assignment]
src/inmanta/agent/cache.py:57: error: Missing type parameters for generic type "contextlib.AbstractContextManager"  [type-arg]
src/inmanta/agent/cache.py:66: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/cache.py:70: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/cache.py:103: error: Attribute "nextAction" already defined on line 92  [no-redef]
src/inmanta/agent/cache.py:232: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/protocol/rest/server.py:28: error: Module "pyformance" has no attribute "timer"  [attr-defined]
src/inmanta/protocol/rest/server.py:297: error: Argument 1 to "get_global_url_map" of "RESTServer" has incompatible type "Sequence[CallTarget]"; expected "List[CallTarget]"  [arg-type]
src/inmanta/protocol/rest/server.py:306: error: Argument 1 to "Application" has incompatible type "List[Rule]"; expected "Optional[List[Union[Rule, List[Any], Tuple[Union[str, Matcher], Any], Tuple[Union[str, Matcher], Any, Dict[str, Any]], Tuple[Union[str, Matcher], Any, Dict[str, Any], str]]]]"  [arg-type]
src/inmanta/protocol/rest/server.py:306: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/protocol/rest/server.py:306: note: Consider using "Sequence" instead, which is covariant
src/inmanta/protocol/rest/client.py:50: error: No overload variant of "get" of "Config" matches argument types "str", "str", "int"  [call-overload]
src/inmanta/protocol/rest/client.py:50: note: Possible overload variants:
src/inmanta/protocol/rest/client.py:50: note:     def get(cls) -> ConfigParser
src/inmanta/protocol/rest/client.py:50: note:     def get(cls, section: str, name: str, default_value: Optional[str] = ...) -> Optional[str]
src/inmanta/protocol/rest/client.py:74: error: Value expression in dictionary comprehension has incompatible type "str"; expected type "bytes"  [misc]
src/inmanta/protocol/rest/client.py:84: error: No overload variant of "get" of "Config" matches argument types "str", "str", "int"  [call-overload]
src/inmanta/protocol/rest/client.py:84: note: Possible overload variants:
src/inmanta/protocol/rest/client.py:84: note:     def get(cls) -> ConfigParser
src/inmanta/protocol/rest/client.py:84: note:     def get(cls, section: str, name: str, default_value: Optional[str] = ...) -> Optional[str]
src/inmanta/protocol/rest/client.py:85: error: Incompatible types in assignment (expression has type "Optional[str]", variable has type "str")  [assignment]
src/inmanta/protocol/rest/client.py:111: error: Incompatible types in assignment (expression has type "Union[bytes, str]", variable has type "Optional[Dict[str, Any]]")  [assignment]
src/inmanta/protocol/rest/client.py:123: error: Argument "body" to "HTTPRequest" has incompatible type "Optional[Dict[str, Any]]"; expected "Union[bytes, str, None]"  [arg-type]
src/inmanta/protocol/rest/client.py:146: error: Returning Any from function declared to return "Result"  [no-any-return]
src/inmanta/protocol/rest/client.py:148: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/protocol/rest/client.py:154: error: Argument "result" to "Result" has incompatible type "str"; expected "Optional[Dict[str, Any]]"  [arg-type]
src/inmanta/protocol/rest/client.py:156: error: Argument "result" to "Result" has incompatible type "str"; expected "Optional[Dict[str, Any]]"  [arg-type]
src/inmanta/protocol/rest/client.py:159: error: Argument "result" to "Result" has incompatible type "bytes"; expected "Optional[Dict[str, Any]]"  [arg-type]
src/inmanta/plugins.py:59: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/plugins.py:73: error: Too many arguments for "normalize" of "DynamicStatement"  [call-arg]
src/inmanta/plugins.py:75: error: Unexpected keyword argument "provides" for "ExecutionUnit"  [call-arg]
src/inmanta/plugins.py:132: error: Module "tornado.ioloop" does not explicitly export attribute "TimeoutError"; implicit reexport disabled  [attr-defined]
src/inmanta/plugins.py:146: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/plugins.py:206: error: Missing type parameters for generic type "Tuple"  [type-arg]
src/inmanta/plugins.py:229: error: Missing type parameters for generic type "Tuple"  [type-arg]
src/inmanta/plugins.py:482: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/plugins.py:486: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/plugins.py:503: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/execute/runtime.py:917: note: "ExecutionUnit" defined here
src/inmanta/plugins.py:135: error: Returning Any from function declared to return "T"  [no-any-return]
src/inmanta/plugins.py:149: error: Argument 1 to "add_function" of "PluginMeta" has incompatible type "PluginMeta"; expected "Type[Plugin]"  [arg-type]
src/inmanta/plugins.py:159: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:208: error: "Type[Plugin]" has no attribute "__function__"  [attr-defined]
src/inmanta/plugins.py:214: error: "Type[Plugin]" has no attribute "__function__"  [attr-defined]
src/inmanta/plugins.py:217: error: "Type[Plugin]" has no attribute "__function__"  [attr-defined]
src/inmanta/plugins.py:251: error: Value of type "Optional[Tuple[Any, ...]]" is not indexable  [index]
src/inmanta/plugins.py:255: error: Argument 1 to "append" of "list" has incompatible type "Tuple[str, Any]"; expected "Tuple[str, Any, Any]"  [arg-type]
src/inmanta/plugins.py:260: error: Incompatible return value type (got "List[Tuple[str, Any, Any]]", expected "List[Tuple[Any, ...]]")  [return-value]
src/inmanta/plugins.py:260: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/plugins.py:260: note: Consider using "Sequence" instead, which is covariant
src/inmanta/plugins.py:260: note: Perhaps you need a type annotation for "arguments"? Suggestion: "List[Tuple[Any, ...]]"
src/inmanta/plugins.py:280: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:293: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:310: error: Argument 4 to "LocatableString" has incompatible type "None"; expected "Namespace"  [arg-type]
src/inmanta/plugins.py:334: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/plugins.py:334: error: "Type[object]" has no attribute "validate"  [attr-defined]
src/inmanta/plugins.py:359: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:367: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:377: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:382: error: Argument 1 to "is_valid" has incompatible type "Tuple[Any, ...]"; expected "Tuple[Optional[Type[object]], str]"  [arg-type]
src/inmanta/plugins.py:382: error: Argument 2 to "is_valid" has incompatible type "Optional[Type]"; expected "Type[object]"  [arg-type]
src/inmanta/plugins.py:391: error: Argument 1 to "is_valid" has incompatible type "Tuple[str, ...]"; expected "Tuple[Optional[Type[object]], str]"  [arg-type]
src/inmanta/plugins.py:391: error: Argument 2 to "is_valid" has incompatible type "Optional[Type]"; expected "Type[object]"  [arg-type]
src/inmanta/plugins.py:394: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:402: error: Incompatible return value type (got "None", expected "DynamicStatement")  [return-value]
src/inmanta/plugins.py:405: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/plugins.py:405: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/plugins.py:411: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/plugins.py:412: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/plugins.py:417: error: "Plugin" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:436: error: "Plugin" has no attribute "call"  [attr-defined]
src/inmanta/plugins.py:445: error: Argument 2 to "_is_instance" of "Plugin" has incompatible type "Type"; expected "Type[object]"  [arg-type]
src/inmanta/plugins.py:458: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:464: error: "Type[Plugin]" has no attribute "__function_name__"  [attr-defined]
src/inmanta/plugins.py:508: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/plugins.py:513: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/plugins.py:546: error: Returning Any from function declared to return "Callable[..., Any]"  [no-any-return]
src/inmanta/ast/variables.py:77: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:78: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:80: error: Incompatible types in assignment (expression has type "Union[Type, ResultVariable[Any]]", target has type "VariableABC[Any]")  [assignment]
src/inmanta/ast/variables.py:84: error: Missing type parameters for generic type "ResultCollector"  [type-arg]
src/inmanta/ast/variables.py:85: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:86: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:87: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/variables.py:87: error: Incompatible types in assignment (expression has type "Union[Type, ResultVariable[Any]]", variable has type "ResultVariable[Any]")  [assignment]
src/inmanta/ast/variables.py:133: error: Argument 1 to "Reference" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/ast/variables.py:210: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:264: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:271: error: Missing type parameters for generic type "ResultCollector"  [type-arg]
src/inmanta/ast/variables.py:274: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:275: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/variables.py:280: error: Need type annotation for "temp"  [var-annotated]
src/inmanta/ast/variables.py:282: error: Missing type parameters for generic type "VariableReader"  [type-arg]
src/inmanta/ast/variables.py:311: error: Argument 2 to "AttributeReference" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/ast/statements/generator.py:103: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:104: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:113: error: Argument 2 of "execute" is incompatible with supertype "RequiresEmitStatement"; supertype defines the argument type as "Resolver"  [override]
src/inmanta/ast/statements/generator.py:113: note: This violates the Liskov substitution principle
src/inmanta/ast/statements/generator.py:113: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
src/inmanta/ast/statements/generator.py:170: error: Argument 2 of "receive_result" is incompatible with supertype "ResultCollector"; supertype defines the argument type as "Location"  [override]
src/inmanta/ast/statements/generator.py:170: note: This violates the Liskov substitution principle
src/inmanta/ast/statements/generator.py:170: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
src/inmanta/ast/statements/generator.py:170: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/generator.py:216: error: "BasicBlock" has no attribute "requires"  [attr-defined]
src/inmanta/ast/statements/generator.py:219: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:221: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:248: error: "object" has no attribute "receive_result"  [attr-defined]
src/inmanta/ast/statements/generator.py:284: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:285: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:347: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:348: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:351: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/generator.py:390: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/generator.py:394: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/generator.py:396: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:505: error: Incompatible types in assignment (expression has type "Type", variable has type "EntityLike")  [assignment]
src/inmanta/ast/statements/generator.py:554: error: "Constructor" has no attribute "get_default_values"  [attr-defined]
src/inmanta/ast/statements/generator.py:557: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:558: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:580: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/statements/generator.py:588: error: Item "None" of "Optional[EntityLike]" has no attribute "get_entity"  [union-attr]
src/inmanta/ast/statements/generator.py:598: error: Item "None" of "Optional[EntityLike]" has no attribute "get_entity"  [union-attr]
src/inmanta/ast/statements/generator.py:600: error: Item "None" of "Optional[EntityLike]" has no attribute "get_full_name"  [union-attr]
src/inmanta/ast/statements/generator.py:631: error: Argument 2 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/ast/statements/generator.py:650: error: Argument 1 to "copy_location" of "Locatable" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/ast/statements/generator.py:671: error: Argument 4 to "SetAttributeHelper" has incompatible type "Dict[object, VariableABC[Any]]"; expected "Dict[object, ResultVariable[Any]]"  [arg-type]
src/inmanta/ast/statements/generator.py:677: error: Argument 1 to "append" of "list" has incompatible type "Optional[Tracker]"; expected "Tracker"  [arg-type]
src/inmanta/ast/statements/generator.py:757: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/generator.py:758: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/agent/io/__init__.py:98: error: Returning Any from function declared to return "None"  [no-any-return]
src/inmanta/agent/io/__init__.py:99: error: Incompatible return value type (got "object", expected "IOBase")  [return-value]
src/inmanta/server/protocol.py:107: error: Argument 1 to "RESTServer" has incompatible type "SessionManager"; expected "SessionManagerInterface"  [arg-type]
src/inmanta/server/protocol.py:354: error: Argument 1 to "append" of "list" has incompatible type "Tuple[str, Type[RedirectHandler], Dict[str, str]]"; expected "Rule"  [arg-type]
src/inmanta/server/protocol.py:371: error: Call to untyped function "distribution" in typed context  [no-untyped-call]
src/inmanta/server/protocol.py:429: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/server/protocol.py:446: error: Incompatible types in assignment (expression has type "object", variable has type "None")  [assignment]
src/inmanta/server/protocol.py:465: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/server/protocol.py:477: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/server/protocol.py:478: error: Need type annotation for "future"  [var-annotated]
src/inmanta/server/protocol.py:524: error: Module has no attribute "TimeoutError"  [attr-defined]
src/inmanta/server/protocol.py:530: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/server/protocol.py:595: error: Argument 1 to "start" of "RESTServer" has incompatible type "dict_values[str, ServerSlice]"; expected "Sequence[CallTarget]"  [arg-type]
src/inmanta/server/protocol.py:612: error: Item "None" of "Optional[HTTPServer]" has no attribute "_sockets"  [union-attr]
src/inmanta/server/protocol.py:615: error: Item "None" of "Optional[HTTPServer]" has no attribute "_sockets"  [union-attr]
src/inmanta/server/protocol.py:631: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/server/protocol.py:725: error: Dict entry 0 has incompatible type "str": "List[Request]"; expected "str": "str"  [dict-item]
src/inmanta/ast/statements/call.py:73: error: Incompatible types in assignment (expression has type "Location", base class "Locatable" defined the type as "property")  [assignment]
src/inmanta/ast/statements/call.py:94: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/statements/call.py:95: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/statements/call.py:98: error: Need type annotation for "temp"  [var-annotated]
src/inmanta/ast/statements/call.py:103: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/statements/call.py:107: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/statements/call.py:111: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
src/inmanta/ast/statements/call.py:115: error: Item "None" of "Optional[Function]" has no attribute "call_direct"  [union-attr]
src/inmanta/ast/statements/call.py:117: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/statements/call.py:128: error: Item "None" of "Optional[Function]" has no attribute "call_in_context"  [union-attr]
src/inmanta/ast/statements/call.py:162: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/ast/statements/call.py:168: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/ast/statements/call.py:168: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/call.py:190: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/call.py:203: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/ast/statements/call.py:209: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/ast/statements/call.py:226: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/call.py:230: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/ast/statements/call.py:237: error: "Plugin" has no attribute "opts"  [attr-defined]
src/inmanta/ast/statements/call.py:268: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/ast/statements/call.py:268: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/call.py:285: error: Call to untyped function "resume" in typed context  [no-untyped-call]
src/inmanta/ast/statements/call.py:291: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/entity.py:37: error: Module "inmanta.execute.runtime" does not explicitly export attribute "dataflow"; implicit reexport disabled  [attr-defined]
src/inmanta/ast/entity.py:125: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/entity.py:181: error: Return type "Dict[str, Optional[ExpressionStatement]]" of "_get_own_defaults" incompatible with return type "Dict[str, ExpressionStatement]" in supertype "EntityLike"  [override]
src/inmanta/ast/entity.py:226: error: Incompatible types in assignment (expression has type "property", variable has type "Dict[str, Attribute]")  [assignment]
src/inmanta/ast/entity.py:391: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/ast/entity.py:429: error: Argument 1 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/ast/entity.py:429: error: Argument 2 to "DuplicateException" has incompatible type "Instance"; expected "Locatable"  [arg-type]
src/inmanta/ast/entity.py:439: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/entity.py:496: error: Returning Any from function declared to return "Location"  [no-any-return]
src/inmanta/ast/entity.py:542: error: Returning Any from function declared to return "Location"  [no-any-return]
src/inmanta/ast/entity.py:554: error: Incompatible types in assignment (expression has type "None", variable has type "ExpressionStatement")  [assignment]
src/inmanta/ast/entity.py:575: error: Incompatible types in assignment (expression has type "None", variable has type "Entity")  [assignment]
src/inmanta/ast/entity.py:583: error: Incompatible types in assignment (expression has type "EntityLike", variable has type "Entity")  [assignment]
src/inmanta/ast/entity.py:584: error: List item 0 has incompatible type "EntityLike"; expected "Entity"  [list-item]
src/inmanta/ast/entity.py:599: error: "Default" has no attribute "_entity"; maybe "entity", "set_entity", or "get_entity"?  [attr-defined]
src/inmanta/ast/entity.py:600: error: "Default" has no attribute "_entity"; maybe "entity", "set_entity", or "get_entity"?  [attr-defined]
src/inmanta/ast/entity.py:626: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/ast/entity.py:626: error: "Default" has no attribute "__name"; maybe "name"?  [attr-defined]
src/inmanta/ast/constraint/expression.py:69: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:72: error: Argument 2 to "register_operator" of "Operator" has incompatible type "OpMetaClass"; expected "Type[Operator]"  [arg-type]
src/inmanta/ast/constraint/expression.py:84: error: Argument 1 to "__init__" of "ReferenceStatement" has incompatible type "List[Reference]"; expected "List[ExpressionStatement]"  [arg-type]
src/inmanta/ast/constraint/expression.py:84: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
src/inmanta/ast/constraint/expression.py:84: note: Consider using "Sequence" instead, which is covariant
src/inmanta/ast/constraint/expression.py:88: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/constraint/expression.py:89: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/constraint/expression.py:91: error: Need type annotation for "temp"  [var-annotated]
src/inmanta/ast/constraint/expression.py:160: error: Call to untyped function "_op" in typed context  [no-untyped-call]
src/inmanta/ast/constraint/expression.py:163: error: Call to untyped function "_op" in typed context  [no-untyped-call]
src/inmanta/ast/constraint/expression.py:168: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/ast/constraint/expression.py:172: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:177: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:186: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:190: error: Missing positional argument "expression" in call to "create_function"  [call-arg]
src/inmanta/ast/constraint/expression.py:190: error: Argument 1 to "create_function" has incompatible type "Operator"; expected "ConstraintType"  [arg-type]
src/inmanta/ast/constraint/expression.py:209: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:247: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/constraint/expression.py:248: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/ast/constraint/expression.py:250: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/constraint/expression.py:270: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/constraint/expression.py:319: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/ast/constraint/expression.py:344: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/handler.py:67: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/handler.py:130: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/agent/handler.py:135: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/agent/handler.py:139: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/agent/handler.py:369: error: Argument 1 to "json_encode" has incompatible type "object"; expected "Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]"  [arg-type]
src/inmanta/agent/handler.py:380: error: Argument 3 to "log" of "LogLine" has incompatible type "**Dict[str, object]"; expected "Optional[datetime]"  [arg-type]
src/inmanta/agent/handler.py:381: error: Argument "exc_info" to "log" of "Logger" has incompatible type "object"; expected "Union[None, bool, Union[Tuple[Type[BaseException], BaseException, Optional[TracebackType]], Tuple[None, None, None]], BaseException]"  [arg-type]
src/inmanta/agent/handler.py:496: error: Argument 2 to "chain_future" has incompatible type "concurrent.futures._base.Future[T]"; expected "asyncio.futures.Future[Any]"  [arg-type]
src/inmanta/agent/handler.py:641: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/server/extensions.py:127: error: Returning Any from function declared to return "Dict[str, Dict[str, Any]]"  [no-any-return]
src/inmanta/server/extensions.py:170: error: Returning Any from function declared to return "bool"  [no-any-return]
src/inmanta/parser/plyInmantaLex.py:68: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/parser/plyInmantaLex.py:84: error: Argument 1 to "get" of "dict" has incompatible type "Union[str, LocatableString]"; expected "str"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:85: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/parser/plyInmantaLex.py:94: error: Argument 1 to "LocatableString" has incompatible type "Union[str, LocatableString]"; expected "str"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:135: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/parser/plyInmantaLex.py:153: error: Incompatible types in assignment (expression has type "float", variable has type "Union[str, LocatableString]")  [assignment]
src/inmanta/parser/plyInmantaLex.py:153: error: Argument 1 to "float" has incompatible type "Union[str, LocatableString]"; expected "Union[SupportsFloat, SupportsIndex, str, bytes, array[Any], mmap, _CData, PickleBuffer]"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:159: error: Incompatible types in assignment (expression has type "int", variable has type "Union[str, LocatableString]")  [assignment]
src/inmanta/parser/plyInmantaLex.py:159: error: Argument 1 to "int" has incompatible type "Union[str, LocatableString]"; expected "Union[str, bytes, array[Any], mmap, _CData, PickleBuffer, SupportsInt, SupportsIndex, SupportsTrunc]"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:165: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/parser/plyInmantaLex.py:181: error: Argument 1 to "Reference" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:183: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/parser/plyInmantaLex.py:184: error: Incompatible types in assignment (expression has type "Regex", variable has type "Union[str, LocatableString]")  [assignment]
src/inmanta/parser/plyInmantaLex.py:198: error: Argument 1 to "len" has incompatible type "Union[str, LocatableString]"; expected "Sized"  [arg-type]
src/inmanta/parser/plyInmantaLex.py:211: error: Value of type "Union[str, LocatableString]" is not indexable  [index]
src/inmanta/export.py:64: error: Missing type parameters for generic type "tuple"  [type-arg]
src/inmanta/export.py:89: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/export.py:154: error: List comprehension has incompatible type List[Union[None, str, Tuple[object, ...], float, DynamicProxy]]; expected List[Dict[str, Sequence[Union[str, Tuple[Any, ...], float, DynamicProxy]]]]  [misc]
src/inmanta/export.py:176: error: Argument 3 to "create_from_model" of "Resource" has incompatible type "Union[None, str, Tuple[object, ...], float, DynamicProxy]"; expected "DynamicProxy"  [arg-type]
src/inmanta/export.py:253: error: Unexpected keyword argument "types"  [call-arg]
src/inmanta/export.py:255: error: Too few arguments  [call-arg]
src/inmanta/export.py:351: error: Returning Any from function declared to return "int"  [no-any-return]
src/inmanta/export.py:351: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/export.py:410: error: Argument 1 to "json_encode" has incompatible type "List[Dict[str, Any]]"; expected "Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]"  [arg-type]
src/inmanta/export.py:422: error: Argument 4 to "commit_resources" of "Exporter" has incompatible type "Optional[Dict[str, Any]]"; expected "Dict[Any, Any]"  [arg-type]
src/inmanta/export.py:443: error: Argument 1 to "set_version" of "Resource" has incompatible type "Optional[int]"; expected "int"  [arg-type]
src/inmanta/export.py:497: error: Missing type parameters for generic type "Dict"  [type-arg]
src/inmanta/export.py:531: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/export.py:575: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/export.py:576: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/export.py:582: error: Incompatible return value type (got "Optional[int]", expected "int")  [return-value]
src/inmanta/export.py:642: error: Argument 2 to "add" of "Exporter" has incompatible type "Tuple[str, ...]"; expected "List[str]"  [arg-type]
src/inmanta/export.py:699: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
src/inmanta/export.py:703: error: Call to untyped function "ReferenceValue" in typed context  [no-untyped-call]
src/inmanta/export.py:718: error: "Type" has no attribute "get_full_name"  [attr-defined]
src/inmanta/export.py:720: error: Argument 1 to "relation_name" has incompatible type "Type"; expected "Entity"  [arg-type]
src/inmanta/export.py:753: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/export.py:760: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/export.py:760: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/export.py:768: error: Call to untyped function "convert" in typed context  [no-untyped-call]
src/inmanta/export.py:770: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/export.py:796: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/export.py:797: error: Need type annotation for "attributes" (hint: "attributes: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/export.py:798: error: Need type annotation for "relations" (hint: "relations: Dict[<type>, <type>] = ...")  [var-annotated]
src/inmanta/export.py:809: error: Call to untyped function "convert_entity" in typed context  [no-untyped-call]
src/inmanta/ast/statements/define.py:466: error: Incompatible types in assignment (expression has type "property", variable has type "ExpressionStatement")  [assignment]
src/inmanta/ast/statements/define.py:547: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/ast/statements/define.py:552: error: Argument 1 to "HyphenDeprecationWarning" has incompatible type "Optional[LocatableString]"; expected "LocatableString"  [arg-type]
src/inmanta/ast/statements/define.py:555: error: Argument 1 to "HyphenDeprecationWarning" has incompatible type "Optional[LocatableString]"; expected "LocatableString"  [arg-type]
src/inmanta/ast/statements/define.py:619: error: Argument 1 to "set_multiplicity" of "RelationAttribute" has incompatible type "Optional[Tuple[int, Optional[int]]]"; expected "Tuple[int, Optional[int]]"  [arg-type]
src/inmanta/ast/statements/define.py:632: error: Argument 1 to "set_multiplicity" of "RelationAttribute" has incompatible type "Optional[Tuple[int, Optional[int]]]"; expected "Tuple[int, Optional[int]]"  [arg-type]
src/inmanta/ast/statements/define.py:740: error: Return type "None" of "register_types" incompatible with return type "Tuple[str, NamedType]" in supertype "TypeDefinitionStatement"  [override]
src/inmanta/ast/statements/define.py:741: error: Incompatible types in assignment (expression has type "Optional[Namespace]", variable has type "Namespace")  [assignment]
src/inmanta/server/bootloader.py:40: error: Incompatible return value type (got "Iterator[ModuleInfo]", expected "Generator[ModuleInfo, None, None]")  [return-value]
src/inmanta/server/bootloader.py:168: error: Returning Any from function declared to return "Callable[[ApplicationContext], None]"  [no-any-return]
src/inmanta/parser/plyInmantaParser.py:170: error: Argument 1 to "DefineImport" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/parser/plyInmantaParser.py:176: error: Argument 1 to "DefineImport" has incompatible type "str"; expected "LocatableString"  [arg-type]
src/inmanta/parser/plyInmantaParser.py:516: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
src/inmanta/parser/plyInmantaParser.py:524: error: Incompatible types in assignment (expression has type "Tuple[object, ...]", variable has type "Tuple[str, str]")  [assignment]
src/inmanta/parser/plyInmantaParser.py:679: error: Call to untyped function "Not" in typed context  [no-untyped-call]
src/inmanta/parser/plyInmantaParser.py:1161: error: "str" has no attribute "location"  [attr-defined]
src/inmanta/execute/scheduler.py:56: error: Module "inmanta.ast" has no attribute "BasicBlock"  [attr-defined]
src/inmanta/execute/scheduler.py:56: error: Module "inmanta.ast" does not explicitly export attribute "NamedType"; implicit reexport disabled  [attr-defined]
src/inmanta/execute/scheduler.py:56: error: Module "inmanta.ast" does not explicitly export attribute "Statement"; implicit reexport disabled  [attr-defined]
src/inmanta/execute/scheduler.py:147: error: "Type" has no attribute "get_all_instances"  [attr-defined]
src/inmanta/execute/scheduler.py:153: error: "Type" has no attribute "get_all_instances"  [attr-defined]
src/inmanta/execute/scheduler.py:159: error: "Type" has no attribute "get_all_instances"  [attr-defined]
src/inmanta/execute/scheduler.py:250: error: "DefinitionStatement" has no attribute "evaluate"  [attr-defined]
src/inmanta/execute/scheduler.py:326: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/scheduler.py:335: error: Missing type parameters for generic type "VariableABC"  [type-arg]
src/inmanta/execute/scheduler.py:424: error: Argument 2 to "requeue_with_additional_requires" of "Waiter" has incompatible type "Optional[Instance]"; expected "ResultVariable[Any]"  [arg-type]
src/inmanta/execute/scheduler.py:562: error: Missing type parameters for generic type "DelayedResultVariable"  [type-arg]
src/inmanta/execute/scheduler.py:588: error: "<subclass of "DelayedResultVariable" and "RelationAttributeVariable">" has no attribute "attribute"  [attr-defined]
src/inmanta/execute/scheduler.py:589: error: "<subclass of "DelayedResultVariable" and "RelationAttributeVariable">" has no attribute "attribute"  [attr-defined]
src/inmanta/execute/scheduler.py:590: error: "<subclass of "DelayedResultVariable" and "RelationAttributeVariable">" has no attribute "attribute"  [attr-defined]
src/inmanta/compiler/__init__.py:51: error: Module "inmanta.ast" has no attribute "BasicBlock"  [attr-defined]
src/inmanta/compiler/__init__.py:51: error: Module "inmanta.ast" does not explicitly export attribute "Statement"; implicit reexport disabled  [attr-defined]
src/inmanta/compiler/__init__.py:95: error: Incompatible types in assignment (expression has type "Optional[Namespace]", variable has type "Namespace")  [assignment]
src/inmanta/compiler/__init__.py:233: error: Incompatible types in assignment (expression has type "Optional[Namespace]", variable has type "Namespace")  [assignment]
src/inmanta/compiler/__init__.py:301: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/module.py:89: error: Skipping analyzing "pkg_resources.packaging.version": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/module.py:99: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:131: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/module.py:131: error: "Requirement" has no attribute "specifier"  [attr-defined]
src/inmanta/module.py:993: error: Returning Any from function declared to return "Mapping[str, object]"  [no-any-return]
src/inmanta/module.py:1095: error: Argument 1 to "Metadata" has incompatible type "**Mapping[str, object]"; expected "str"  [arg-type]
src/inmanta/module.py:1095: error: Argument 1 to "Metadata" has incompatible type "**Mapping[str, object]"; expected "Optional[str]"  [arg-type]
src/inmanta/module.py:1095: error: Argument 1 to "Metadata" has incompatible type "**Mapping[str, object]"; expected "bool"  [arg-type]
src/inmanta/module.py:1206: error: Returning Any from function declared to return "str"  [no-any-return]
src/inmanta/module.py:1439: error: Invalid type comment or annotation  [valid-type]
src/inmanta/module.py:1439: note: Suggestion: use constr[...] instead of constr(...)
src/inmanta/module.py:1492: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
src/inmanta/module.py:1496: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
src/inmanta/module.py:1498: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
src/inmanta/module.py:1767: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:1791: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:1955: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:1967: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2054: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
src/inmanta/module.py:2070: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2086: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2135: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2164: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2349: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2368: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2370: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2531: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2532: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2534: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/module.py:2899: error: "str" has no attribute "filter"  [attr-defined]
src/inmanta/env.py:40: error: Module "pkg_resources" has no attribute "DistInfoDistribution"  [attr-defined]
src/inmanta/env.py:251: error: "Type[WorkingSet]" has no attribute "_build_master"  [attr-defined]
src/inmanta/env.py:557: error: Argument "requirements" to "_run_pip_install_command" of "PythonEnvironment" has incompatible type "Sequence[Requirement]"; expected "Optional[List[Requirement]]"  [arg-type]
src/inmanta/env.py:738: error: "Requirement" has no attribute "name"  [attr-defined]
src/inmanta/env.py:744: error: "Requirement" has no attribute "url"  [attr-defined]
src/inmanta/env.py:829: error: Argument "requirements" to "_run_pip_install_command" of "PythonEnvironment" has incompatible type "Sequence[Requirement]"; expected "Optional[List[Requirement]]"  [arg-type]
src/inmanta/env.py:985: error: Incompatible return value type (got "Optional[Tuple[Optional[str], Optional[Loader]]]", expected "Optional[Tuple[Optional[str], Loader]]")  [return-value]
src/inmanta/env.py:1002: error: Item "None" of "Optional[ModuleSpec]" has no attribute "submodule_search_locations"  [union-attr]
src/inmanta/env.py:1003: error: Item "None" of "Optional[ModuleSpec]" has no attribute "submodule_search_locations"  [union-attr]
src/inmanta/env.py:1209: error: Module has no attribute "real_prefix"  [attr-defined]
src/inmanta/app.py:69: error: Skipping analyzing "rpdb": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/app.py:90: error: Missing type parameters for generic type "Future"  [type-arg]
src/inmanta/app.py:92: error: Argument 2 to "safe_shutdown" has incompatible type "Callable[[Optional[int]], Coroutine[Any, Any, None]]"; expected "Callable[[], None]"  [arg-type]
src/inmanta/app.py:98: error: Argument 2 to "safe_shutdown" has incompatible type "Callable[[Optional[int]], Coroutine[Any, Any, None]]"; expected "Callable[[], None]"  [arg-type]
src/inmanta/app.py:173: error: Argument 2 to "signal" has incompatible type "Callable[[Signals, Optional[FrameType]], None]"; expected "Union[Callable[[int, Optional[FrameType]], Any], int, Handlers, None]"  [arg-type]
src/inmanta/app.py:174: error: Argument 2 to "signal" has incompatible type "Callable[[Signals, Optional[FrameType]], None]"; expected "Union[Callable[[int, Optional[FrameType]], Any], int, Handlers, None]"  [arg-type]
src/inmanta/app.py:175: error: Argument 2 to "signal" has incompatible type "Callable[[Signals, Optional[FrameType]], None]"; expected "Union[Callable[[int, Optional[FrameType]], Any], int, Handlers, None]"  [arg-type]
src/inmanta/app.py:603: error: Argument 1 to "run" of "Exporter" has incompatible type "Optional[Dict[str, Type]]"; expected "Optional[Dict[str, Entity]]"  [arg-type]
src/inmanta/app.py:617: error: Argument 1 to "ModelExporter" has incompatible type "Optional[Dict[str, Type]]"; expected "Dict[str, Entity]"  [arg-type]
src/inmanta/app.py:683: error: "object" not callable  [operator]
src/inmanta/app.py:713: error: Missing type parameters for generic type "StreamHandler"  [type-arg]
src/inmanta/app.py:761: error: Incompatible types in assignment (expression has type "Formatter", variable has type "ColoredFormatter")  [assignment]
src/inmanta/moduletool.py:36: error: Skipping analyzing "texttable": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/moduletool.py:38: error: Skipping analyzing "cookiecutter.main": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/moduletool.py:148: error: Function is missing a type annotation  [no-untyped-def]
src/inmanta/moduletool.py:290: error: Incompatible types in assignment (expression has type "TextIOWrapper", variable has type "Optional[str]")  [assignment]
src/inmanta/moduletool.py:293: error: Incompatible types in assignment (expression has type "TextIO", variable has type "Optional[str]")  [assignment]
src/inmanta/moduletool.py:295: error: Incompatible types in assignment (expression has type "TextIOWrapper", variable has type "Optional[str]")  [assignment]
src/inmanta/moduletool.py:299: error: Item "str" of "Optional[str]" has no attribute "write"  [union-attr]
src/inmanta/moduletool.py:299: error: Item "None" of "Optional[str]" has no attribute "write"  [union-attr]
src/inmanta/moduletool.py:302: error: Item "str" of "Optional[str]" has no attribute "close"  [union-attr]
src/inmanta/moduletool.py:302: error: Item "None" of "Optional[str]" has no attribute "close"  [union-attr]
src/inmanta/moduletool.py:425: error: Need type annotation for "_mod_handled_list" (hint: "_mod_handled_list: Set[<type>] = ...")  [var-annotated]
src/inmanta/moduletool.py:596: error: Missing type parameters for generic type "ModuleLike"  [type-arg]
src/inmanta/moduletool.py:625: error: Incompatible types in assignment (expression has type "Module[Any]", variable has type "str")  [assignment]
src/inmanta/moduletool.py:627: error: "str" has no attribute "GENERATION"  [attr-defined]
src/inmanta/moduletool.py:660: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/moduletool.py:670: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/moduletool.py:673: error: Argument 1 to "get_project_for_module" of "ModuleTool" has incompatible type "None"; expected "str"  [arg-type]
src/inmanta/moduletool.py:680: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/moduletool.py:771: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/moduletool.py:800: error: "Module[Any]" has no attribute "is_editable"  [attr-defined]
src/inmanta/moduletool.py:830: error: Missing type parameters for generic type Module  [type-arg]
src/inmanta/moduletool.py:897: error: Incompatible types in assignment (expression has type "Module[Any]", variable has type "Optional[str]")  [assignment]
src/inmanta/moduletool.py:899: error: Item "str" of "Optional[str]" has no attribute "name"  [union-attr]
src/inmanta/moduletool.py:899: error: Item "None" of "Optional[str]" has no attribute "name"  [union-attr]
src/inmanta/moduletool.py:949: error: Incompatible types in assignment (expression has type "TextIO", variable has type "Optional[TextIOWrapper]")  [assignment]
src/inmanta/moduletool.py:955: error: Item "None" of "Optional[TextIOWrapper]" has no attribute "write"  [union-attr]
src/inmanta/moduletool.py:958: error: Item "None" of "Optional[TextIOWrapper]" has no attribute "close"  [union-attr]
src/inmanta/execute/dataflow/graphic.py:54: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/dataflow/graphic.py:61: error: Missing type parameters for generic type "ResultVariable"  [type-arg]
src/inmanta/execute/dataflow/graphic.py:83: error: Missing type parameters for generic type "Assignment"  [type-arg]
src/inmanta/execute/dataflow/graphic.py:148: error: Missing type parameters for generic type "Assignment"  [type-arg]
src/inmanta/deploy.py:50: error: Missing type parameters for generic type "Popen"  [type-arg]
src/inmanta/deploy.py:200: error: Returning Any from function declared to return "Optional[str]"  [no-any-return]
src/inmanta/deploy.py:200: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:209: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:224: error: Unsupported right operand type for in ("Optional[Dict[str, Any]]")  [operator]
src/inmanta/deploy.py:224: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:225: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:264: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:281: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:386: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:400: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:439: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/deploy.py:471: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/compiler/help/explainer.py:137: error: Missing return statement  [return]
src/inmanta/compiler/help/explainer.py:142: error: Item "None" of "Optional[Reference]" has no attribute "pretty_print"  [union-attr]
src/inmanta/compiler/help/explainer.py:147: error: Item "None" of "Optional[RelationAttribute]" has no attribute "get_name"  [union-attr]
src/inmanta/server/validate_filter.py:103: error: Incompatible return value type (got "Callable[[object], Optional[List[Tuple[RangeOperator, int]]]]", expected "Callable[[object, object], Optional[List[Tuple[RangeOperator, int]]]]")  [return-value]
src/inmanta/server/validate_filter.py:103: error: Incompatible return value type (got "Callable[[object], Optional[List[Tuple[RangeOperator, datetime]]]]", expected "Callable[[object, object], Optional[List[Tuple[RangeOperator, datetime]]]]")  [return-value]
src/inmanta/server/validate_filter.py:125: error: Missing type parameters for generic type "classmethod"  [type-arg]
src/inmanta/server/validate_filter.py:150: error: Too few arguments  [call-arg]
src/inmanta/server/validate_filter.py:164: error: Too few arguments  [call-arg]
src/inmanta/server/validate_filter.py:297: error: Unexpected keyword argument "field" for "Filter"  [call-arg]
src/inmanta/server/services/metricservice.py:64: error: Argument "tags" to "InfluxReporter" has incompatible type "Collection[str]"; expected "Dict[str, str]"  [arg-type]
src/inmanta/server/services/metricservice.py:132: error: Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
src/inmanta/server/services/databaseservice.py:100: error: Incompatible return value type (got "Dict[str, object]", expected "Dict[str, Union[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]], Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]]]]")  [return-value]
src/inmanta/server/diff.py:33: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
src/inmanta/server/diff.py:47: error: Incompatible return value type (got "Optional[str]", expected "str")  [return-value]
src/inmanta/protocol/openapi/converter.py:26: error: Module "typing_inspect" has no attribute "get_args"  [attr-defined]
src/inmanta/protocol/openapi/converter.py:26: error: Module "typing_inspect" has no attribute "get_origin"  [attr-defined]
src/inmanta/protocol/openapi/converter.py:55: error: Returning Any from function declared to return "Union[Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None], JSONSerializable]"  [no-any-return]
src/inmanta/protocol/openapi/converter.py:167: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[str]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[List[str]]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[Schema]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[Dict[str, Schema]]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Union[Schema, bool, None]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[bool]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:176: error: Argument 1 to "Schema" has incompatible type "**Dict[str, object]"; expected "Optional[Sequence[Schema]]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:179: error: Missing type parameters for generic type "Type"  [type-arg]
src/inmanta/protocol/openapi/converter.py:181: error: Variable "type_annotation" is not valid as a type  [valid-type]
src/inmanta/protocol/openapi/converter.py:181: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
src/inmanta/protocol/openapi/converter.py:186: error: Value of type "Optional[Dict[str, Schema]]" is not indexable  [index]
src/inmanta/protocol/openapi/converter.py:202: error: Value of type "Optional[Dict[str, Schema]]" is not indexable  [index]
src/inmanta/protocol/openapi/converter.py:273: error: Missing type parameters for generic type "Callable"  [type-arg]
src/inmanta/protocol/openapi/converter.py:307: error: Incompatible return value type (got "List[Union[Parameter, Reference]]", expected "List[Parameter]")  [return-value]
src/inmanta/protocol/openapi/converter.py:347: error: Missing type parameters for generic type "Dict"  [type-arg]
src/inmanta/protocol/openapi/converter.py:382: error: Argument "parameters" to "Operation" has incompatible type "Optional[List[Parameter]]"; expected "Optional[List[Union[Parameter, Reference]]]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:386: error: Argument 7 to "Operation" has incompatible type "**Dict[str, RequestBody]"; expected "Optional[bool]"  [arg-type]
src/inmanta/protocol/openapi/converter.py:392: error: "CallTarget" has no attribute "_name"  [attr-defined]
src/inmanta/main.py:29: error: Skipping analyzing "texttable": module is installed, but missing library stubs or py.typed marker  [import]
src/inmanta/main.py:83: error: Returning Any from function declared to return "Optional[Dict[str, Any]]"  [no-any-return]
src/inmanta/main.py:685: error: Value of type "object" is not indexable  [index]
src/inmanta/main.py:733: error: Invalid index type "str" for "str"; expected type "Union[SupportsIndex, slice]"  [index]
src/inmanta/main.py:758: error: Value of type "Optional[Dict[str, Any]]" is not indexable  [index]
src/inmanta/db/versions/v202105170.py:55: error: Missing type parameters for generic type "Dict"  [type-arg]
src/inmanta/db/versions/v202105170.py:71: error: "object" has no attribute "__iter__"; maybe "__str__" or "__dir__"? (not iterable)  [attr-defined]
src/inmanta/data/paging.py:120: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:120: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:120: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:149: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:149: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:149: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:178: error: Argument "total" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:178: error: Argument "before" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:178: error: Argument "after" to "PagingCounts" has incompatible type "object"; expected "int"  [arg-type]
src/inmanta/data/paging.py:216: error: Argument 3 to "count_items_for_paging" of "Compile" has incompatible type "Union[UUID, str, None]"; expected "Optional[UUID]"  [arg-type]
src/inmanta/data/paging.py:216: error: Argument 4 to "count_items_for_paging" of "Compile" has incompatible type "Union[UUID, str, None]"; expected "Optional[UUID]"  [arg-type]
src/inmanta/data/paging.py:588: error: Argument "start" to "PagingBoundaries" has incompatible type "Optional[datetime]"; expected "Union[datetime, int, str]"  [arg-type]
src/inmanta/data/paging.py:590: error: Argument "end" to "PagingBoundaries" has incompatible type "Optional[datetime]"; expected "Union[datetime, int, str]"  [arg-type]
src/inmanta/data/paging.py:595: error: Argument "start" to "PagingBoundaries" has incompatible type "Optional[datetime]"; expected "Union[datetime, int, str]"  [arg-type]
src/inmanta/data/paging.py:597: error: Argument "end" to "PagingBoundaries" has incompatible type "Optional[datetime]"; expected "Union[datetime, int, str]"  [arg-type]
src/inmanta/server/services/compilerservice.py:240: error: Item "None" of "Optional[Dict[str, Any]]" has no attribute "items"  [union-attr]
src/inmanta/server/services/compilerservice.py:316: error: Item "None" of "Optional[Environment]" has no attribute "repo_url"  [union-attr]
src/inmanta/server/services/compilerservice.py:317: error: Item "None" of "Optional[Environment]" has no attribute "repo_branch"  [union-attr]
src/inmanta/server/services/compilerservice.py:405: error: No overload variant of "get" of "Config" matches argument types "str", "str", "bool"  [call-overload]
src/inmanta/server/services/compilerservice.py:405: note: Possible overload variants:
src/inmanta/server/services/compilerservice.py:405: note:     def get(cls) -> ConfigParser
src/inmanta/server/services/compilerservice.py:405: note:     def get(cls, section: str, name: str, default_value: Optional[str] = ...) -> Optional[str]
src/inmanta/server/services/compilerservice.py:420: error: Argument 1 to "update" of "MutableMapping" has incompatible type "Optional[Dict[str, Any]]"; expected "SupportsKeysAndGetItem[str, str]"  [arg-type]
src/inmanta/server/services/compilerservice.py:499: error: Missing type parameters for generic type "Task"  [type-arg]
src/inmanta/server/services/compilerservice.py:518: error: Module has no attribute "state_dir"  [attr-defined]
src/inmanta/server/services/compilerservice.py:586: error: Incompatible types in assignment (expression has type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]", variable has type "bool")  [assignment]
src/inmanta/server/services/compilerservice.py:699: error: Incompatible return value type (got "float", expected "int")  [return-value]
src/inmanta/server/services/compilerservice.py:711: error: Item "None" of "Optional[Environment]" has no attribute "get"  [union-attr]
src/inmanta/server/services/compilerservice.py:719: error: Argument 2 to "_calculate_recompile_wait" of "CompilerService" has incompatible type "Optional[datetime]"; expected "datetime"  [arg-type]
src/inmanta/server/services/compilerservice.py:752: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/server/services/compilerservice.py:834: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[CompilerService, Environment, Optional[int], Optional[UUID], Optional[UUID], Optional[datetime], Optional[datetime], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[CompileReport]]]]"  [type-var]
src/inmanta/server/services/compilerservice.py:871: error: Argument 8 to "get_compile_reports" of "Compile" has incompatible type "**Dict[str, Tuple[QueryType, object]]"; expected "Optional[Connection]"  [arg-type]
src/inmanta/server/services/notificationservice.py:117: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[NotificationService, Environment, Optional[int], Optional[UUID], Optional[UUID], Optional[datetime], Optional[datetime], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[Notification]]]]"  [type-var]
src/inmanta/server/server.py:71: error: List item 0 has incompatible type "BoolFeature"; expected "Feature[object]"  [list-item]
src/inmanta/server/server.py:127: error: Module has no attribute "state_dir"  [attr-defined]
src/inmanta/server/server.py:133: error: Module has no attribute "log_dir"  [attr-defined]
src/inmanta/server/server.py:197: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[Server, Optional[ApiDocsFormat]], Coroutine[Any, Any, ReturnValue[Union[OpenAPI, str]]]]"  [type-var]
src/inmanta/server/server.py:199: error: Argument 1 to "get_global_url_map" of "RESTServer" has incompatible type "dict_values[str, ServerSlice]"; expected "List[CallTarget]"  [arg-type]
src/inmanta/server/agentmanager.py:291: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/server/agentmanager.py:866: error: Module has no attribute "handle"  [attr-defined]
src/inmanta/server/agentmanager.py:866: error: Untyped decorator makes function "get_agents" untyped  [misc]
src/inmanta/server/agentmanager.py:905: error: Argument "start" to "get_agents" of "Agent" has incompatible type "Union[datetime, int, str, None]"; expected "Union[datetime, bool, str, None]"  [arg-type]
src/inmanta/server/agentmanager.py:906: error: Argument "end" to "get_agents" of "Agent" has incompatible type "Union[datetime, int, str, None]"; expected "Union[datetime, bool, str, None]"  [arg-type]
src/inmanta/server/agentmanager.py:908: error: Argument 8 to "get_agents" of "Agent" has incompatible type "**Dict[str, Tuple[QueryType, object]]"; expected "Optional[Connection]"  [arg-type]
src/inmanta/server/agentmanager.py:931: error: Module has no attribute "handle"  [attr-defined]
src/inmanta/server/agentmanager.py:931: error: Untyped decorator makes function "get_agent_process_details" untyped  [misc]
src/inmanta/server/agentmanager.py:938: error: "int" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "ReturnValue[Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]]" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "ReturnValue[None]" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "UUID" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "StrictNonIntBool" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "float" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: "datetime" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:938: error: Unpacking a string is disallowed  [misc]
src/inmanta/server/agentmanager.py:938: error: "None" object is not iterable  [misc]
src/inmanta/server/agentmanager.py:940: error: Incompatible types in assignment (expression has type "Union[Any, Dict[str, Any], None, Tuple[str, Any], BaseModel, UUID, StrictNonIntBool, float, datetime, str]", variable has type "Optional[Dict[str, Union[Dict[str, List[str]], Dict[str, str], Dict[str, float], str]]]")  [assignment]
src/inmanta/server/agentmanager.py:1175: error: Item "None" of "Optional[Process]" has no attribute "pid"  [union-attr]
src/inmanta/server/agentmanager.py:1218: error: Argument 1 to "join" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/inmanta/server/services/resourceservice.py:101: error: Argument "args" to "__init__" of "LogRecord" has incompatible type "List[<nothing>]"; expected "Optional[Union[Tuple[object, ...], Mapping[str, object]]]"  [arg-type]
src/inmanta/server/services/resourceservice.py:109: error: Module has no attribute "_startTime"  [attr-defined]
src/inmanta/server/services/resourceservice.py:158: error: Module has no attribute "log_dir"  [attr-defined]
src/inmanta/server/services/resourceservice.py:333: error: Incompatible types in assignment (expression has type "Tuple[Set[ResourceVersionIdStr], Set[ResourceVersionIdStr]]", variable has type "Optional[Tuple[Set[ResourceVersionIdStr], List[ResourceVersionIdStr]]]")  [assignment]
src/inmanta/server/services/resourceservice.py:336: error: "None" object is not iterable  [misc]
src/inmanta/server/services/resourceservice.py:481: error: Argument "changes" to "set_and_save" of "ResourceAction" has incompatible type "Dict[ResourceVersionIdStr, Dict[str, Dict[str, Any]]]"; expected "Dict[str, Any]"  [arg-type]
src/inmanta/server/services/resourceservice.py:502: error: Incompatible types in assignment (expression has type "ResourceVersionIdStr", variable has type "Id")  [assignment]
src/inmanta/server/services/resourceservice.py:701: error: Argument 2 to "mark_done_if_done" of "ConfigurationModel" has incompatible type "Optional[int]"; expected "int"  [arg-type]
src/inmanta/server/services/resourceservice.py:719: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, Id, UUID], Coroutine[Any, Any, Dict[ResourceVersionIdStr, ResourceState]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:764: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, Optional[str], Optional[str], Optional[str], Optional[str], Optional[str], Optional[int], Optional[UUID], Optional[datetime], Optional[datetime]], Coroutine[Any, Any, ReturnValue[List[ResourceAction]]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:821: error: Missing type parameters for generic type "dict"  [type-arg]
src/inmanta/server/services/resourceservice.py:848: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, Id], Coroutine[Any, Any, Dict[ResourceIdStr, List[ResourceAction]]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:927: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, Optional[int], Optional[ResourceVersionIdStr], Optional[ResourceVersionIdStr], Optional[str], Optional[str], Optional[Dict[str, List[str]]], str, bool], Coroutine[Any, Any, ReturnValue[List[LatestReleasedResource]]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:1001: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, ResourceIdStr, Optional[int], Optional[str], Optional[str], Optional[datetime], Optional[datetime], str], Coroutine[Any, Any, ReturnValue[List[ResourceHistory]]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:1058: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, ResourceIdStr, Optional[int], Optional[datetime], Optional[datetime], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[ResourceLog]]]]"  [type-var]
src/inmanta/server/services/resourceservice.py:1108: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ResourceService, Environment, int, Optional[int], Optional[ResourceVersionIdStr], Optional[ResourceVersionIdStr], Optional[str], Optional[str], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[VersionedResource]]]]"  [type-var]
src/inmanta/server/services/paramservice.py:124: error: Argument 2 to "request_parameter" of "AgentManager" has incompatible type "str"; expected "ResourceIdStr"  [arg-type]
src/inmanta/server/services/paramservice.py:132: error: Unsupported operand types for + ("None" and "timedelta")  [operator]
src/inmanta/server/services/paramservice.py:132: note: Left operand is of type "Optional[datetime]"
src/inmanta/server/services/paramservice.py:132: error: Unsupported operand types for > ("timedelta" and "datetime")  [operator]
src/inmanta/server/services/paramservice.py:132: note: Left operand is of type "Union[datetime, timedelta]"
src/inmanta/server/services/paramservice.py:136: error: Argument 2 to "request_parameter" of "AgentManager" has incompatible type "str"; expected "ResourceIdStr"  [arg-type]
src/inmanta/server/services/paramservice.py:301: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ParameterService, Environment, Optional[int], Optional[UUID], Optional[UUID], Union[datetime, str, None], Union[datetime, str, None], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[Parameter]]]]"  [type-var]
src/inmanta/server/services/paramservice.py:342: error: Argument "start" to "get_parameter_list" of "Parameter" has incompatible type "Union[datetime, int, str, None]"; expected "Optional[datetime]"  [arg-type]
src/inmanta/server/services/paramservice.py:343: error: Argument "end" to "get_parameter_list" of "Parameter" has incompatible type "Union[datetime, int, str, None]"; expected "Optional[datetime]"  [arg-type]
src/inmanta/server/services/paramservice.py:369: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[ParameterService, Environment, Optional[int], Optional[UUID], Optional[UUID], Optional[str], Optional[str], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[Fact]]]]"  [type-var]
src/inmanta/server/services/dryrunservice.py:124: error: Function is missing a return type annotation  [no-untyped-def]
src/inmanta/server/services/dryrunservice.py:162: error: Incompatible types in assignment (expression has type "int", target has type "UUID")  [assignment]
src/inmanta/server/services/orchestrationservice.py:132: error: Argument 1 to "is_update" of "ResourceWithResourceSet" has incompatible type "Optional[ResourceWithResourceSet]"; expected "ResourceWithResourceSet"  [arg-type]
src/inmanta/server/services/orchestrationservice.py:331: error: Generator has incompatible item type "Optional[str]"; expected "str"  [misc]
src/inmanta/server/services/orchestrationservice.py:382: error: Unsupported operand types for > ("int" and "StrictNonIntBool")  [operator]
src/inmanta/server/services/orchestrationservice.py:382: error: Unsupported operand types for > ("int" and "str")  [operator]
src/inmanta/server/services/orchestrationservice.py:382: error: Unsupported operand types for > ("int" and "Dict[str, Union[str, int, StrictNonIntBool]]")  [operator]
src/inmanta/server/services/orchestrationservice.py:382: note: Right operand is of type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"
src/inmanta/server/services/orchestrationservice.py:383: error: Unsupported operand types for - ("int" and "StrictNonIntBool")  [operator]
src/inmanta/server/services/orchestrationservice.py:383: error: Unsupported operand types for - ("int" and "str")  [operator]
src/inmanta/server/services/orchestrationservice.py:383: error: Unsupported operand types for - ("int" and "Dict[str, Union[str, int, StrictNonIntBool]]")  [operator]
src/inmanta/server/services/orchestrationservice.py:383: note: Right operand is of type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"
src/inmanta/server/services/orchestrationservice.py:386: error: Unsupported operand type for unary - ("Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]")  [operator]
src/inmanta/server/services/orchestrationservice.py:386: error: Slice index must be an integer or None  [misc]
src/inmanta/server/services/orchestrationservice.py:445: error: Argument 1 to "append" of "list" has incompatible type "Resource"; expected "Dict[str, Any]"  [arg-type]
src/inmanta/server/services/orchestrationservice.py:448: error: Unsupported target for indexed assignment ("Resource")  [index]
src/inmanta/server/services/orchestrationservice.py:449: error: Value of type "Resource" is not indexable  [index]
src/inmanta/server/services/orchestrationservice.py:720: error: Incompatible types in assignment (expression has type "Dict[<nothing>, <nothing>]", target has type "Union[UUID, StrictNonIntBool, int, float, datetime, str]")  [assignment]
src/inmanta/server/services/orchestrationservice.py:807: error: Incompatible types in assignment (expression has type "Set[Optional[str]]", variable has type "Set[str]")  [assignment]
src/inmanta/server/services/orchestrationservice.py:991: error: Value of type variable "FuncT" of "__call__" of "handle" cannot be "Callable[[OrchestrationService, Environment, Optional[int], Optional[int], Optional[int], Optional[Dict[str, List[str]]], str], Coroutine[Any, Any, ReturnValue[List[DesiredStateVersion]]]]"  [type-var]
src/inmanta/server/services/orchestrationservice.py:1068: error: "int" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "ReturnValue[Union[BaseModel, UUID, StrictNonIntBool, int, float, datetime, str, Sequence[Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], Mapping[str, Union[BaseModel, Union[UUID, StrictNonIntBool, int, float, datetime, str]]], None]]" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "ReturnValue[None]" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "UUID" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "StrictNonIntBool" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "float" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "datetime" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: Unpacking a string is disallowed  [misc]
src/inmanta/server/services/orchestrationservice.py:1068: error: "None" object is not iterable  [misc]
src/inmanta/server/services/orchestrationservice.py:1072: error: Argument 1 to "BaseHttpException" has incompatible type "Union[Any, Tuple[str, Any], BaseModel, UUID, StrictNonIntBool, float, datetime, str]"; expected "int"  [arg-type]
src/inmanta/server/services/orchestrationservice.py:1072: error: Value of type "Union[Any, Dict[str, Any], None, Tuple[str, Any], BaseModel, UUID, StrictNonIntBool, float, datetime, str]" is not indexable  [index]
src/inmanta/server/services/orchestrationservice.py:1072: error: Invalid tuple index type (actual type "str", expected type "Union[int, slice]")  [misc]
src/inmanta/server/services/orchestrationservice.py:1072: error: Invalid index type "str" for "Union[Any, Dict[str, Any], None, Tuple[str, Any], BaseModel, UUID, StrictNonIntBool, float, datetime, str]"; expected type "Union[SupportsIndex, slice]"  [index]
src/inmanta/server/services/environmentservice.py:174: error: Argument 2 to "schedule_full_compile" of "CompilerService" has incompatible type "Union[StrictNonIntBool, int, float, str, Dict[str, Union[str, int, StrictNonIntBool]]]"; expected "str"  [arg-type]
src/inmanta/server/services/environmentservice.py:436: error: Incompatible types in assignment (expression has type "UUID", target has type "str")  [assignment]
Generated Cobertura report: /home/florent/Desktop/inmanta-core/coverage/cobertura.xml
Found 1333 errors in 82 files (checked 131 source files)
